### ISSUE TITLE
Feature: Material Gauge Selection list Reorder v2.0.12

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#10]
**Issue:**
Material Guage in the selection drop down in ordered in a way that doesn't make sense
We would like it Reordered From Thinnest to Thickest Gauge size.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/0b475f31-f25e-4392-932f-9de133188f85)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.0)
