### ISSUE TITLE
Bug: Migration from 1.0 to 2.0 Continued...

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#103]
Reference bug Ore-Design/Ore-3D-Reports-Changelog#93 

Copy Issues:
•	Predesigned:
o	A1021-S 
	Not Pulling in IPE BOM (Same as 1.0)
	Unit Price $683.17 Vs 1.0: $1,398

o	A1022-S 
	Not Pulling in IPE BOM (Same as 1.0)
	Unit Price $660.19 Vs 1.0: $1,412
	SQFT of Material is Lower than 1.0

o	S1116-R 
	Not Pulling in IPE BOM (1.0 Does pull in IPE)
	0 CAD (Finishing is Higher in 1.0)

o	A1021-S 
	Not Pulling in IPE BOM (Same as 1.0)
	Unit Price $683.17 Vs 1.0: $1,398

o	A1027-S 
	Unit Price $1,051 Vs 1.0: $1,374
	0 CAD
	100-5022 - 1.5’ Less than 1.0

o	C1026-R
	Unit Price $1,779 Vs 1.0: $1,421
	0 CAD
	100-5022 - 1.5’ Less than 1.0

o	A1018-S 
	0 CAD
	140-1012 Missing

o	C1025-R 
	0 CAD
	102-5009 – 1.5’ Less than 1.0

o	A1121-Z 
	0 CAD
	100-6003 &100-6004 Missing

o	A3005-S
	0 CAD
	Finishing 5 Min vs 39 min/1.0
	100-2008 Missing

•	What Worked:
o	Descriptions match exactly.

•	Test Proposal:
o	47917 – 1.0
o	47919 – 2.0

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
