### ISSUE TITLE
Feature: Lock Order in Netsuite when Open in Ore3D

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#104]
**Bug:**
Proposal 47919 was in Status: Out to Customers
After Saving proposal Status Changed to: Sales without user input
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/337f6a79-1b4a-4fce-afec-eb3033489341)

**Comment by CBarsell** [comment]
Noticed proposal was open in 2.0 when netsuite status changes. After save it reverted status back to what it was when opened. 
I would be neat if netsuite could give us a notification if proposal in Currently open in Ore3D

**Comment by Reyzerbit** [comment]
Done 😄
