### ISSUE TITLE
6000 series Facil planters are pulling the wrong inventory item

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#105]
Example:

A6021 - pulling 100-6028 - needs to be pulling 100-6027

<img width="1271" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/88e6a820-cb09-43fd-85e9-b4cdc6c2a253">

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
