### ISSUE TITLE
Bison Planter Change to Modified when Zinc finish is added

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#106]
Bison planters need to change to -Z when zinc is selcted as finish:

<img width="1106" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/d52d02f3-0d37-4773-9f43-0e6ba79430b3">

**Comment by Reyzerbit** [comment]
I fix it 😄
