### ISSUE TITLE
Bug: Custom FF Issues

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#107]
- ~~Why is FAB for pans and lids more then doubled in 2.0?~~ Ore3D 1.0 didn't properly multiply for Tig weld

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/349fd682-571f-4b21-bd7a-ff8698dea0d6)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/88287934-d369-4dda-b214-8b77863b4cf9)

- Burner is hidden in Pan and does not display to customer.
For custom FF, can we enter the burner as a BOM item instead of in the pan child?
How are we supposed to enter custom burners if they don't show up in the burner drop down?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/ae4b8ed8-0168-4f1b-91cd-e62b309612b9)

- What does the "Matches Parent" button do?
   I was under the impression it was supposed to pull dims from the pan and auto fill.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/2865887e-98ec-4040-99af-b7c5ae69ea6c)

**Comment by daniel11088** [comment]
How are clips calculated for glass surrounds?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6d6254a1-dd15-4016-88b8-2dc281b758d2)

**Comment by Reyzerbit** [comment]
Note: Glass clip count was being multiplied by Pi for rectangular because of copy/paste logic from 1.0

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
