### ISSUE TITLE
Bug: Predesigned Benches v2.0.12

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#11]
**Bug:**
Pre designed benches are showing no FAB time in the routings
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/34395b19-076f-4fcb-bdd0-5c7effbdb958)

**Comment by jdrake89** [comment]
Meeting set 3/1/24 @Reyzerbit

**Comment by jdrake89** [comment]
Meeting Notes:

Ties into overall shape code project. 
Locking benches (all) into static values (labor times/material).
Using as built data / fab recommendations - Lacey collect labor times for all models (EOD 3/4/24) .
Jake BOM review (EOD 3/5/24)
Push compilations through Estimating to produce proposals for IT to input into Ore3D (EOD 3/8/24).
Shape Code Completion in Ore3D (3/11/24)

**Comment by jdrake89** [comment]
https://docs.google.com/spreadsheets/d/16shYSNVVw1e0rN0DFFVi7QOPOhEMArppSwxQClnuoRo/edit#gid=2035183892

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.13](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.13)
