### ISSUE TITLE
Feature: UNLOCK (NetSuite) - Doesn't work with new feature

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#111]
REF: 46958

This was locked on 3/8.

With the new NetSuite feature that doesn't allow editing for 'open' orders also prevents us from unlocking a proposal that isn't actively in use. 

1 idea would be to leave the blue banner, but add the edit button back on so we unlock proposals if/when needed. 

Open to alternate ideas too.

**Comment by Reyzerbit** [comment]
@mxidis what was our plan for this?

**Comment by mxidis** [comment]
I think i'd still like to leave this in an admin thing in Netsuite.  I'll create a permission-based search that'll show all locked records and then we can give permission to that search to remove the lock.
