### ISSUE TITLE
(106-2038) NetSuite item not copying to 2.0 from 1.0

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#115]
106-2038 NetSuite item not copying to 2.0 from 1.0
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/b3fde8fe-4724-4124-a7cf-52147e24a4b3)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/30901d7a-e702-4d9f-95db-0ae3dd63ec17)

**Comment by Reyzerbit** [comment]
Transferring this to Jake Drake, this is related to Netsuite Data.

**Comment by Reyzerbit** [comment]
Fixed by @jdrake89

**Comment by jdrake89** [comment]
@jjohnson2525 I've set this price to $60 per sq/ft in the system for now. Let me know if there are any issues.
