### ISSUE TITLE
1.0 to 2.0 conversion

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#116]
•	Catalog price not accurate for all Pre-Designs
•	NetSuite subtotal does not match 2.0 subtotal
•	Items are showing 1.0 price in 2.0 but different price in Netsuite
•	Quantity not transferring for all items
•	Pre-Designed items being changed to Custom during transfer

[noreply@ore.design_20240326_141405.pdf](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/14764743/noreply%40ore.design_20240326_141405.pdf)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
