### ISSUE TITLE
Band Planter Pre-Designed Issue

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#118]
Reveal Height adjustment changes it from Predesigned to Custom

Reveal type none should autolock reveal height to 0

https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/107

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/46f53fe9-9506-4657-9ea8-11b4e7676118)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
