### ISSUE TITLE
Bug: S1206 BOM Error

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#119]
1206 (all materials)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/2b4bcce2-c98a-4801-a57d-b04637f9fd95)

pre-designed pricing is correct - this appears to only impact the BOM.

**Comment by Reyzerbit** [comment]
Note to Self: Height value not reading properly, refactor to fix.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
