### ISSUE TITLE
Feature: Add option to search for standard product by name [Version 2.012]

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#12]
Lots of standard items are only able to be searched by product number. Please add option to search by names similar to ORE 3D 1.0

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/a59c856e-9604-4681-a362-3bb29f8de57c)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/059bbc87-4e32-4dee-b94c-28b59207173e)

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
