### ISSUE TITLE
Bug: UNABLE TO PROCESS PROPOSAL TO SALES ORDER

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#120]
REF: 47963

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/1cdf7f8e-13f0-444b-a2d5-76ff4cb895e1)

PLEASE SEND MATT ISRAEL A TEAMS MESSAGE DIRECTLY WHEN THIS IS RESOLVED / PROCESSED INTO A SALES ORDER!

This is a test proposal for WO creation, but it's in our production system so Micah & accounting need a heads up because they will show up as real bookings and need to be deleted later.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
