### ISSUE TITLE
Bug: 1.0 copy to 2.0: lbs of powder coat and finish not matching on copy for modified planters

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#124]
1.0 example 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/55b52993-68d1-4860-8095-699ca2f3d76b)

2.0 example
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/8a907a3b-22dc-4ac9-8653-9ec7edb41a4a)

**Comment by Reyzerbit** [comment]
This is expected, feel free to come talk to me if you have any questions.

**Comment by Reyzerbit** [comment]
Not resolved, seems to be intermittent, keep an eye out.
