### ISSUE TITLE
Child drip tray is broken

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#13]
- 100-5022 AL square tube does not change based on dims.
- No option to add skid
- No lip option (Drip trays do not get a lip but unable to select "no lips")

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/26656714-c31b-4df3-a82f-903497a9080c)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/db15a85d-9429-4873-86d1-0bed110beb4f)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
