### ISSUE TITLE
1.0 orders being locked and unable to unlock to change status

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#130]
How do we get orders unlocked?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6948b220-07f5-475c-8cc8-1644380518ec)

**Comment by daniel11088** [comment]
I can make changes to the order in ORE3D but am unable to change anything in netsuite

**Comment by Reyzerbit** [comment]
Pretty sure @mxidis has since resolved this.
