### ISSUE TITLE
Bug: 1.0 to 2.0 Conversion Cont. v2.1.0

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#132]
REF: 
47820 (1.0)
48002 (2.0)

INCOMPLETE REVIEW: Conversion appears to have worked, but 2.0 prices don't match the 2.0 proposal in netsuite (48002).

**Comment by daniel11088** [comment]
~~Weight not showing up~~ Moved to #135

**Comment by daniel11088** [comment]
~~FF doubling components cost but doubling quantity.~~
~~Material sqft in 1.0 - 22.95~~
~~Material sqft in 2.1 - 38.5167~~

Moved to #136

**Comment by daniel11088** [comment]
3 different prices:
46776 1.0 - $35884.50
48006 2.1 - $39987.50
48006 in Netsuite - $55480.25

**Comment by Reyzerbit** [comment]
Note for @daniel11088: weight bug moved into its own issue #125

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.19](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.19)
