### ISSUE TITLE
Bug: A6000 Series summary

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#133]
Summary of updates needed for the A6000 series. Really only 2-3 issues affecting each item. 

A6001: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6002: 1.Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6003: 1.Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6004: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6005: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6006: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6021: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6022: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6023: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6024: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6025: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6026: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6081: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake..
A6082: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6083: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6084: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6085: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6086: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6101: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6102: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6103: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6104: 1. Update Facil Calculator to correct cladding qty, 2. Review description name with Jake.
A6105: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.
A6106: 1. Slat facil not added to BOM. 2. Update Facil Calculator to correct cladding qty, 3. Review description name with Jake.

**Comment by Reyzerbit** [comment]
@jdrake89 let me know when you have some time for a quick review of the 6000 series

**Comment by jdrake89** [comment]
@Reyzerbit I'm backing in receiving today, come back when you can to chat

**Comment by jjohnson2525** [comment]
A6021 - I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Please review.
A6022 - I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Please review.
A6023 - I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Also, FAB should be higher than the horizontal orientation as this vertical orientation has more facil cuts. Please review.
A6024 - I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Also, FAB should be higher than the horizontal orientation as this vertical orientation has more facil cuts. Please review.
A6025 -  I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Also, FAB should be lower than the rail conditions as this slat condition has fewer facil cuts. Please review.
A6026 - I believe you have Facil qty per (1) long and (1) short side. Should be (2) long sides. Also, FAB should be lower than the rail conditions as this slat condition has fewer facil cuts. Please review.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.20](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.20)

**Comment by jjohnson2525** [comment]
A6083 - Add 3/16 for fins and 60mins FAB. FAB low? This is probably good, but let's double check
A6084 - Add 3/16" for fins and 60 mins FAB. FAB low? This is probably good, but let's double check 
A6085 - Add 3/16" for fins and 60 mins FAB. Is 3.5 mins still being added to these? 
A6086 - Add 3/16" for fins and 60 mins FAB. Is 3.5 mins still being added to these? 
A6103 - Add 3/16" for fins and 60 mins FAB. FAB low? This is probably good, but let's double check
A6104 - Add 3/16" for fins and 60 mins FAB. FAB low? This is probably good, but let's double check
A6105 - Add 3/16" for fins and 60 mins FAB. Is 3.5 mins still being added to these? 
A6106 - Add 3/16" for fins and 60 mins FAB. Is 3.5 mins still being added to these?
