### ISSUE TITLE
WO deleted but Ore3D still thinks they exist. S17697

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#134]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/36c783cc-5037-4386-8fd5-04551d5994de)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/6b2baf43-dd6e-4882-b5f3-ad64422b858e)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.19](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.19)
