### ISSUE TITLE
Proposal Transfer from 1.0 - 2.1 BOM + Pricing Issues

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#137]
Proposal 47917 to 47996
Step: 
1. Copied 47917 in 1.0
2. Opened 47996 (Load Normally) in 2.0

Transfer Issues: 
1. A1021-S 
 - No IPE in BOM (1.0)
 - No CAD (2.0)
 - 0 Weight (2.0)
2. A1022-S 
 - No IPE in BOM (1.0)
 - No CAD (2.0)
 - 0 Weight (2.0)
3. S1116-R
 - (140-1005 x 1, 140-1006 x 1, 140-3002 x 14LF) All in (2.0) BOM Item 
 - No CAD (2.0)
 - 0 Weight (2.0)
4. A1027-S 
 - Unit Price $1,501 (2.0)
 - Unit Price $1,824 (1.0)
 - No CAD (2.0)
 - 0 Weight (2.0)
 5. C1026-R 
 - Unit Price $2,139 (2.0)
 - Unit Price $1,781 (1.0)
 - No CAD (2.0)
 - 0 Weight (2.0)
6. A1018-S 
 -140-1012 x 1 (2.0)
 -140-1012 x 4  (1.0) (Correct amount)
 - No CAD (2.0)
 - 0 Weight (2.0)
7. C1025-R
 - 0 CAD (2.0)
 - 0 weight (2.0)
8. A1121-Z
  - 0 CAD (2.0)
  - 0 Weight (2.0)
  - 100-6003 - 1LF (2.0) (1.0 - 10.42LF)
  - 100-6004 1LF (2.0) (1.0 - 10.42LF)
9. A3005-C
 - 0 CAD (2.0)
 - 0 Weight (2.0)
 - 20 min Finishing (2.0) 
 - 137 Min Finishing (1.0)
 - 0 FAB (1.0)
 - (140-1008 x 1, 140-1008 x 2) (2.0)
 - Missing Mottled Zinc in BOM (2.0)
 - Missing 100-2008 in BOM (2.0) See FAB Drawings

Things That worked:
1. Descriptions
2. Add on options 
3. notes
4. qty

**Comment by Reyzerbit** [comment]
CAD time has now changed so it will be 0 on all catalog products

**Comment by Reyzerbit** [comment]
Notice for item 9:
Routings have been set to a new static value by @jdrake89 and Lacey. If you believe any of these routings to be incorrect, please talk to us and we can set up a meeting to discuss it.

All the BOM issues you pointed out will still be resolved 😄

**Comment by Reyzerbit** [comment]
Issues regarding pricing issues with POMO and Groove planters (item 4. 1027 and item 5. 1026) to be addressed ( see #138 ).

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.19](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.19)
