### ISSUE TITLE
Other: POMO and GROOVE Shapecodes

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore3DInternal-Reports-Changelog#138]
We need to discuss shapecodes for both the POMO and GROOVE style planters.

**Comment by MattIsrael** [comment]
This is a low priority for estimating. Request working on UI request/other before getting to this.

**Comment by Reyzerbit** [comment]
[Groove Shape Code_4.5.24.pdf](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/14908904/Groove.Shape.Code_4.5.24.pdf)
[Pomo Shape Code_4.5.24.pdf](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/14908906/Pomo.Shape.Code_4.5.24.pdf)

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
