### ISSUE TITLE
Corten/Mild Steel skid not showing in BOM

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#14]
What is being calculated?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e8e863b8-ba22-48aa-aed4-152599119ac7)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/62568d27-c96a-432b-867c-14c2d46d67f2)

**Comment by Reyzerbit** [comment]
Note to Self: Corten bodies use Mild Steel tubing for skids.

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
