### ISSUE TITLE
Feature: Show new transaction # on duplicate

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#140]
When a proposal is duplicated it would be neat if Ore3D would show you the new proposal # after it was done duplicating the 'old' proposal.

**Comment by Reyzerbit** [comment]
@MattIsrael it does already do that 😄 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/10405105/39af73f7-49b1-4aff-a6ab-2e62030b8fed)
