### ISSUE TITLE
Bug: Fire Pit Children Description Formatting Issue

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#143]
Original Title: Bug: Fire Pit Children Dims Mis-Match [Ore3D Version (1.4.1 etc)]
Seen on pans and lids

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/88a51068-92c9-4f9c-837d-2cd6d75db129)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/b609837c-48bd-4e3e-a7d0-574f736e761f)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
