### ISSUE TITLE
Bug: A3008 1.0-2.0 Copy Issue

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#145]
3008 was copied from 1.0 (47820) to 2.0 (48042)
[lines 8 & 9]

- Identified as Pre-Designed in description
- Pricing incorrect (looks like it calculated as custom)
- BOM incorrect (wood component)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
