### ISSUE TITLE
Feature: Reduce Decimal Places

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#146]
Reduce decimal points in all Ore3D and NetSuite fields.

NetSuite Weight: round to nearest 1.0 lb.

All other decimals to .001

**Comment by Reyzerbit** [comment]
Duplicate of [Ore3D Issue #930](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/issues/930)
