### ISSUE TITLE
Feature: Fuse Edging Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#147]
Remove Reveal and Drain Holes from Fuse Edging descriptions. 

These details don't apply to this product type.

**Comment by Reyzerbit** [comment]
Please elaborate. Remove from PARENT descriptions, or from child descriptions?

**Comment by MattIsrael** [comment]
Remove from parent descriptions. Child descriptions do not show anywhere.
