### ISSUE TITLE
Bug: Edging Type: remove Undefined [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#148]
Remove
Edging Type: Undefined

Edging is either anchored or not anchored. There is no 3rd option. 

We can discuss what default is and specifically how this is implemented.  One option would be the checkbox we have in 1.0

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
