### ISSUE TITLE
Feature: Description change IF Ignore Parent Qty is checked for an option

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#149]
Can discuss as a group.

Currently the item description does not change if an option is applied to all children, or just 1.

Idea:
add "/section" to descriptions where the box is NOT checked. 
[if this is viable I need to coordinate with the rest of the stakeholders to make sure this works for them]

**Comment by Reyzerbit** [comment]
this is possible

**Comment by jdrake89** [comment]
Meeting set for 1:30 on 4/8/24

**Comment by jdrake89** [comment]
Add total QTY of add-on options to Parent description. 
Full Description for add-on 
Per meeting dicision - 4/8/24

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
