### ISSUE TITLE
Fuse Piece Length drop down

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#15]
Can we get a drop down or a range for fuse piece length?

Maybe something similar to what we currently have?

Open to different options.

Need to know the limitations of the new ore3d to figure this out.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/64075b2a-96e8-4721-9ead-0bb869a5f155)

**Comment by Reyzerbit** [comment]
We can probably make this a custom tool. I'll look into it.

**Comment by Reyzerbit** [comment]
Used #60 as alternative solution
