### ISSUE TITLE
Feature: Add Open in NetSuite Button after converting to SO

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#150]
When you convert a 2.0 proposal to a sales order it would be nice to have an Open in NetSuite button as we have after saving proposals.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
