### ISSUE TITLE
Feature: Location pop-up: Set Default

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#152]
can we set the Location default to Woods Cross for all proposals EXCEPT if the customer is Bison? 

If not, can we just set the location to Woods Cross? We'll manually change it for Bison orders.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
