### ISSUE TITLE
Bug: Descriptions Prompting Price Override Pop-Up [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#153]
When converting 48055 into S17853 I received a pop-up asking if I wanted to override pricing on description items. These should have no cost - I'm not sure where this is stemming from???

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/6d1e58b1-2165-4987-8e1e-dcb55809ca6e)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
