### ISSUE TITLE
Bug: A5003 1.0 to 2.0 Conversion

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#154]
Original Title: 1.0 to 2.0 conversion bugs cont.

A5003 doesn't completely copy from 1.0 to 2.0 - this is a known quantity and currently on the 'does not convert list'. (reference only)

~~A3008 - _we might need to add this to the 'does not copy list'_~~
~~Description maintained as pre-designed.~~
~~Bench option being added in 2.0 to configurations that already had the bench from 1.0.(REF: 47820 / 48042)~~
~~Custom pricing appears to be flowing through. (possibly due to additional benches in the BOM?)~~
Duplicate of #145

**Comment by MattIsrael** [comment]
1.0: 47820
2.0: 48042

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
