### ISSUE TITLE
Enhancement: Reduce Predesigned Firepit Options Children List

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#155]
Original title: Standard Fire Features - Option add similar to custom fire pits

Lid, Glass Surround, Pan/Burner

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
