### ISSUE TITLE
Custom Fire Pit Lid / Pan / Glass Surround

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#156]
Figure out pseudo code Pans / Lids - Estimating 

Glass Surrounds - Clip QTY, times and find out from CAD what the parameters for glass length needs to be.

**Comment by MattIsrael** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/7321296d-9f13-42bd-be0c-a0b91b69ad4c)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
