### ISSUE TITLE
Enhancement: Add Duplicated Order to Recently Loaded

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#157]
Original Title: 2.0 Doesn't show recently Duplicated Proposal

After duplicating a proposal and saving it in 2.0 the proposal number didn't show up in Recently Loaded Orders window
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/a510eab6-a32b-493e-9588-45413fa99290)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.2)
