### ISSUE TITLE
Bug: Custom Builds Copy from 1.0 to 2.1.1

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#158]
**Bug:**
Custom Fuse Rectangle:
 - Skids BOM QTY are 1/2 as much as they are supposed to calculating

Custom Bowl Planters:
 - Powder coat QTY 1/2 of 1.0 QTY
 - How is this calculating?

Custom Rectangle Fire Feature:
 - In 1.0 Material was overridden
     - transfer to 2.1 doubled BOM line for over ridden material
     - ![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/5ad2c34d-2232-49b3-a66a-4b2c310926cc)
 - Body FAB time is 1/2 as much as 1.0 FAB time
    - why is math so different?
    - ~~Lid is only given 12min of FAB that is too little Review calculations for this.~~ See #156 

Things that worked:
 - Descriptions
 - notes 
 - overridden routings
 - Most Routings and BOMs within acceptable range from 1.0

**Comment by Reyzerbit** [comment]
> - Body FAB time is 1/2 as much as 1.0 FAB time
>   - why is math so different?

It's not different math, its just a different UI thing. In 1.0, all routings would roll up into the parent in the display. 2.0 no longer does that. Sorry for the confusion 😅

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
