### ISSUE TITLE
Bug: Review Shape Code Logic with MI

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#159]
**Bug:**
FAB time for Mod Rectangle Planter is calculating more than Mod Rectangle Fire Feature. 
~~Rectangle Fire Feature FAB time is less than half of 1.0 Calculated FAB time for same Shape code and dims~~ This is expected, see [this comment.](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/158#issuecomment-2035218683)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/2f18fba8-894e-466b-89db-8c181072501f)

**
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/20a1b703-54ff-4c2f-b97f-ab4aa7e2a9da)
 **

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/a94ddc72-9234-4c49-adde-4b8b26dececc)

**Comment by MattIsrael** [comment]
Please close. discussed and no issue exists. 
explained with skirt inset*
