### ISSUE TITLE
PreFab time higher

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#16]
Spoke with Mike and he said that PreFab should be the same.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/0c24942f-89a6-4aab-a9dd-59c47fc4505a)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/3f607190-7565-4c5b-8888-a79c897ec8ab)

**Comment by Reyzerbit** [comment]
Hey @daniel11088 I cant replicate this issue. If you can come show me how to make this happen, that'd be awesome.
