### ISSUE TITLE
Feature: New Item: 4100

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#160]
Batista,

I’m not finding the 4100 in 2.0. It barely made it into 1.0 so it kinda makes sense. 

We need to get this added to 2.0, most likely as a static (not customizable) shape code?? We use this fairly often we this needs to be medium-high on the priority list. 

Shape code [roughly. needs review]: _rectangle+ fire pit lid_
Do we need a new shape code or can we use rectangles and fire pit lids?

Coordinate adding this with Drake and me, should be pretty easy I'm hoping.

**Comment by MattIsrael** [comment]
[PROPANE TANK HOLDER.pdf](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/14858544/PROPANE.TANK.HOLDER.pdf)

**Comment by Reyzerbit** [comment]
@MattIsrael please provide final math for this and ill make it happen. If you simply want me to copy logic for rectangle + lid, I can, but if there are any changes or reviews needed, please complete those and let me know so I can implement it correctly.

**Comment by MattIsrael** [comment]
@Reyzerbit this will be a 'static' shape code. 
REF: C:\Users\misrael\OneDrive - ore inc\Documents - Company Files\03 - CAD\CATALOG PRODUCTS\A4100 - Propane Tank Holder

Routings: 
https://3619299.app.netsuite.com/app/common/item/item.nl?id=207080&whence=
Except:
***Fab=120 minutes***

Operations would like the container and lid to appear as a single element, not as a parent/child.

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
