### ISSUE TITLE
Feature: Move items between transactions

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#161]
Just feeling out the feasibility of moving line items between transactions. Could be function limited by role.

Use cases: 
PM - Change orders
Estimating - bidding large scope in multiple estimates then combining all of them into a single proposal. (sometimes customers ask us to submit 1 proposals per floor even if it would all book together). 

DO NOT DEVELOP WITHOUT FURTHER COORDINATION - WOULD NEED TO TALK TO STAKEHOLDERS TO VERIFY IT WOULD BE USEFUL.

**Comment by Reyzerbit** [comment]
This is already a feature with copy/cut/paste etc
