### ISSUE TITLE
Bug: Overridden Routings at 0 do not remain overridden

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#162]
Original Title: Copy of 46801 (1.0) to 48127 (2.0)

**Bug:**
CAD time was overridden and Zeroed out in 1.0 version
After copy 2.0 added CAD back into line items.

**Comment by CBarsell** [comment]
for this particular proposal I Zeroed out CAD time again for the 2.0 version to finish the sales order test

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
