### ISSUE TITLE
Bug: Zeroed BOMs cause Netsuite Error

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#163]
Original Title: 48127 to S17869

**Bug:**
We had 3 Fire pits with bodies only in a proposal from the 1.0 version 46801. 
After saving the proposal 48127 in 2.0 it showed the 3 bodies we were trying to keep.
after adjusting some notes and zero out CAD again I saved it again.
Reopened it and Israel showed me how to convert to Sales order: S17869
It saved like expected. I opened up the sales order in netsuite and it showed $0 and no line items.
I clicked into the proposal from the sales order page in netsuite and it also showed empty with no line items.
I reopened the proposal 48127 in 2.0 it showed the line items and the subtotal as expected.
I saved it again and refreshed the netsuite page. it was still empty of line items.
I opened the proposal again in 2.0 and now it was empty.  Israel saw all of this and can attest to this event.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.21](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.21)
