### ISSUE TITLE
FACET Shape Code

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#164]
Shape code for the FACET looks pretty dialed. Just need to make a couple changes. 

1. We need to add vertical seam welds when additional wall sheets are required. Max length of wall sheet should be 70"L. Check 70"L vs. the circumference and round up (i.e. 70"Dia=220"Circumference, 220"cir/70"L = 3.14, round up to 4 vertical seam welds)
--- Note: there will always be a min. of 2 vertical seam welds. (i.e. 20"Dia=63"cir, 63"cir/70"L = .9, this would be 2 seam welds even though it round to 1. 

2. Per Grif: make 70"Dia x 52"H as Max dimensions. Anything past this will need to be built as a fuse. 

Let me know if you have any questions

**Comment by Reyzerbit** [comment]
@jjohnson2525 Can you please get Jake Drake, Grif, and Matt Israel all to send me confirmation of this change?

**Comment by MattIsrael** [comment]
@Reyzerbit let me know when you have a second to review this against what you have in Ore3D.

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/10405105/847aa83f-ab11-4dba-85de-54da2902e2fe)

**Comment by MattIsrael** [comment]
THanks! rock and roll.


[Ore Logo]

Matt Israel

Estimating Manager

***@***.******@***.***>
→ 385.249.1980



1972 W 2425 S
Woods Cross, UT 84087



ore.design<https://ore.design/>



________________________________

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.37](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.37)
