### ISSUE TITLE
Bug: SHAPE CODE ADJUSTMENTS: Box, Silo, Drum

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#166]
Due to engineering changes can you please update the default material for all pre-designed boxes, drums and silos to be 1/4"?

I'll have to follow up with labor changes later. 

*Engineering made this change, but failed to inform estimating.

**Comment by Reyzerbit** [comment]
@MattIsrael please have @jdrake89 and Grif confirm that this is the case

**Comment by jdrake89** [comment]
@Reyzerbit @MattIsrael This is good to updated to 1/4" material on my side. Grif should have a full engineering change order signed.

**Comment by MattIsrael** [comment]
> @Reyzerbit @MattIsrael This is good to updated to 1/4" material on my side. Grif should have a full engineering change order signed.

@Reyzerbit please execute the material (BOM) change for now. We'll circle around on the labor at a later time.

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/10405105/ec4110a6-4732-4c61-9fb8-8cc1cef8cd5e)

**Comment by Reyzerbit** [comment]
Completed
