### ISSUE TITLE
Bug: OLD DATA [red] pop-up error on New Proposals [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#167]
I created a brand new proposal, not a copy. When trying to open in 2.0 I received the Old Data Detected error. 

Error showing Ore3D tab in Netsuite with no data. 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/92f22e37-9e67-4ab5-83ce-3c7e6f7f5baa)

**Comment by Reyzerbit** [comment]
This is expected, we have a fix already to go but waiting on @mxidis permission to operate it

**Comment by Reyzerbit** [comment]
Until the fix is out, just click "load normally"
