### ISSUE TITLE
Feature: Auto match child finish to parent

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#168]
Can we have drip trays, etc automatically match the parent finish?

We can edit the child after adding in the event they are going to be different finishes - this would be extremely rare so if it's a little cumbersome that's ok. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/b5d0bb8b-dfe3-4ec8-8542-d99ffc8852c1)

**Comment by Reyzerbit** [comment]
Resolved by changes to predesigned children change
