### ISSUE TITLE
WO not recognized as created - Children WO not being created - Parent WO QTY's overriding 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#169]
S17852 - Created WO's by selecting parent and children. 

It produced 1 WO as a parent with a with 3 items at QTY 1, but the parent at QTY 9 and the overall QTY on the SO 3 / 90.

<img width="441" alt="image" src="https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/3f27b34d-1a19-4b92-993a-bf92b9a4417c">
<img width="700" alt="image" src="https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/fef2eec1-fdc1-42e1-8aee-dc8360050fa3">

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
