### ISSUE TITLE
Oxidized Zinc Patina not an option in new ORE3D

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#17]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1d6b7e92-8a62-4b74-8832-132b60dbd9b7)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/d7c9815e-8ec0-4920-95d3-b4913b29f3fc)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/77907c80-f28f-4cc5-bcab-edd77e0d389b)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/c1660bd3-619f-42ce-a6c7-ea0e54d86f45)

**Comment by daniel11088** [comment]
Oxidized Zinc Patina is only an option in Corten and Mild Steel which is wrong. 
It should only be an option in AL.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/5168d28c-c64a-4fc6-a82e-6bfc683ce319)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
