### ISSUE TITLE
WO Creation deleted an entire line item on S17853 - Testing

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#170]
An entire line item was deleted when I generated a WO on another line item. 

Then Ore3D didn't recognize there was a WO created for the parent on the item (WO30698), and allowed me to generate another (WO30700). 

Its not generating Child WO when both parent and children are selected. 

It wont generate children WO now at all (on this order).

**Comment by Reyzerbit** [comment]
Note: Issue partially due to removal of Undefined option in Edging Type

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
