### ISSUE TITLE
Feature: Can options have a material assigned to them to pre-filter?

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#171]
Example: 
DF or IRR 

Can we assign a material type to these options so they pre-filter based on primary build material?

**Comment by Reyzerbit** [comment]
This is possible if we make drainage fittings and irrigation sleeves an auto-calculated value, which means instead of adding them manually, we would need a formula for how to auto-calculate them.

**Comment by MattIsrael** [comment]
understood. I don't think we want to do that at this point. 

Closing out for now.
