### ISSUE TITLE
WO option creation - WO30710 / S17851 - Drip tray WO not created

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#173]
It put the drip tray in as a line item on the main WO, it did not create a new WO for the drip tray. 

Also it is not being treated like a phantom item similar to an irrigation sleeve. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/89f2f0d3-941d-4f99-899a-6d0b87739c10)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/11ee3966-2927-4bb9-8a24-faac5d5ee8e0)

**Comment by jdrake89** [comment]
@Reyzerbit I deleted all the WO out of this SO btw

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
