### ISSUE TITLE
How does curved FUSE edging calculate Pre-Fab

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#175]
Curved FUSE edging is calculating Pre-Fab at a higher rate after split.
This only occurs with curved FUSE edging.
Curved FUSE planters do not share this so it is specific with curved edging.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/7478f4da-ca9f-403b-841e-94cc3dd92f14)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/2e19265c-1b00-4676-9b74-7c0d85c88e20)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/4b6917b2-60ba-4f22-9cc1-8d3840c78525)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/3d39bcbf-da1d-4a7d-b8b8-30575896f3d5)

**Comment by Reyzerbit** [comment]
Too much to explain all in one comment, please come see me for a full explanation, but from everything I see, this is expected
