### ISSUE TITLE
Irrigation Tube not showing up in BOM for Bison

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#179]
It says it in the description but not in BOM.
Was this intentional? 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/3e88f0e4-2cd6-4fa2-9038-440d72fae3a9)

**Comment by Reyzerbit** [comment]
100-5010 is irrigation tube, this is intentional. Talk to @jdrake89 if you have any questions.
