### ISSUE TITLE
Clone button in FUSE not working properly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#18]
When cloning a child, it creates the clone as a parent and attempts to create a work order.

If TBD is selected as a finish, it generates a error red error message that prevents the order being saved.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/9bb75ea6-4dbf-44c2-86a1-40b2548dca8c)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1e08420e-46cb-4b24-94b9-b186718c1bd6)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
