### ISSUE TITLE
Copying 1.0 to 2.0 auto locks 2.0 orders in netsuite only

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#181]
I can still open the order in 2.0 and make changes but it gets locked in netsuite.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6d6973f6-2bb3-41c9-8f83-ae9ce80d00cc)

**Comment by Reyzerbit** [comment]
@daniel11088 I am unable to replicate this, can you please come show me how you did this?
