### ISSUE TITLE
ORE3D not matching Netsuite

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#182]
I opened an order copied from 1.0 (47830) to 2.1 (48007) and does not match NetSuite.

1.0 (47830) - $663,590.38
2.1.2 (48007) - NetSuite $729,086.08. ORE3D $180,905.44

48007
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/df54a7b4-2329-4db7-b30e-d8b3f79b3e06)

NetSuite
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/0f5341e5-5c9b-4382-8523-12769d0ba348)

**Comment by daniel11088** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/bee91bcb-f11f-45ac-915c-839a3af72e1e)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/68107d39-5887-4244-9a27-d28d741435d0)

**Comment by Reyzerbit** [comment]
See #186
