### ISSUE TITLE
Copying 1.0 to 2.1.2 transfer the over calculation of SQFT in FUSE

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#184]
Resplitting the child in 2.1.2 maintains the same over calculation of SQFT issue in 1.0

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/51c08735-7b58-4229-956d-ec932217edc1)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/455fe663-6a60-46b8-aef3-b9e8e85884e6)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/cc9210f0-d4cc-49ab-9265-9a9af750a4bf)

**Comment by daniel11088** [comment]
This is occurring in both copied orders and new orders

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
