### ISSUE TITLE
SQFT being multiplied by number of sections

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#185]
Before split, material sqft is accurate.

Roughly 10 sqft per section is being added.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/b55abb7a-a1d4-4a67-8cb9-b668176cd0dc)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/a754354d-f6b2-4aa2-86bb-656d8b2500b7)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/5359ebd0-133c-40e9-b3ca-239ba8757fd2)

**Comment by Reyzerbit** [comment]
This is an expected side-affect of the sheet metal yield multiplier. Just don't estimate objects that are over-size, and the issue will no longer persist.
