### ISSUE TITLE
0 reveal adds routing times

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#187]
When 0 reveal type is selected, FAB and Fit up times are increased.

This bug affects FUSE and Non-FUSE.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/3247ee03-96c7-4763-a436-6bab62f5792a)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/93010a09-0fc0-47a4-a614-6d240e67898e)

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
