### ISSUE TITLE
Feature: Title to match Predesigned label

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#188]
Can we get the the title to match the name of the predesign or get name of the predesign to get listed in the description like in 1.0?

A1214 is a round taper but in 2.0 it is called a cone planter and round taper is not listed anywhere in the description.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e4c11db1-73c7-4313-8fbc-8cbfbf54841e)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/bc555870-1ed9-4c1e-88ba-dbe74c28b7ed)

**Comment by daniel11088** [comment]
Any movement on this?

**Comment by Reyzerbit** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/10405105/ad07883e-f386-4a5b-a208-1f477afaf4bf)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.27](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.27)
