### ISSUE TITLE
Copy issue from 1.0 to 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#189]
Predesign changing thickness and price:

A1206 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/9f442ad6-8a17-4031-a8a7-3ed3508074d1)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/63731a8a-ee8c-487e-876f-e1b8bbe06c53)

**Comment by daniel11088** [comment]
Not mathing correctly:

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1078d72e-301b-405c-9d0c-32faa7912de5)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1442cf98-a9b6-41ee-b125-71ef816689d2)

**Comment by Reyzerbit** [comment]
Completed in [1.0.22](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.22)
