### ISSUE TITLE
Bug: Remove Messages related to WOs from Proposal Records [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#192]
Messages relating to WO creation should not be visible when viewing proposals. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/0a6e3eb8-09f4-4def-9897-b9c98c7b5665)

**Comment by Reyzerbit** [comment]
This is not possible. The warnings are calculated based on the build data, not the parent transaction data.
