### ISSUE TITLE
Feature: Show work order number once generated

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#193]
**Issue:**
Need to have the Work Order number listed somewhere within the item to be able to cross reference between sales order information and Ore3D information. 

**Solution:**
Maybe have it show when you hover over the green Work Order symbol that shows after right clicking the line item? Under the 
line description in the right click window on the line item. 

**Alternatives:**
Under the line description in the right click window on the line item. 

**Additional Context/Questions:**

![Screenshot 2024-04-15 132324](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/167131464/ab52ade1-33ca-4877-a3fa-802093e5c0d3)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.26](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.26)
