### ISSUE TITLE
Feature: WO children listed on the parent WO

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#194]
**Issue:**
There is no link or list of the children work orders that go with the parent work order. 

**Solution:**
Related Record tab on the parent work order has a Work Order Children tab within it where children work orders have always appeared. That would be the most convenient location as that is where everyone is used to looking. Children work orders need to be listed somewhere on the parent work order that they are associated with. 

**Alternatives:**
A custom list or something on the Ore3D tab on the parent work order with associated children listed. 

**Additional Context/Questions:**
Related records tab:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/167131464/a548f94a-c136-4a59-bca7-618ac791554c)

**Comment by LackyLou** [comment]
WO30808 is the parent I was working with when I posted this. WO30807 is the child.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.26](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.26)
