### ISSUE TITLE
Other: Effects of Overriding the Description

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#197]
**Details/Question:**
We need to go over the effects of overriding the description. If the finish was TBD when the overriding occurred, then it will forever be that way unless we revert the description which then leads to losing the notes that were put in with the override. 

We cannot have finish TBD on a line item when it gets to the point of scheduling and I am sure we do not want to lose the notes that were put in on the line item that is causing the finish to not update. 

We need to have chat.

**Comment by Reyzerbit** [comment]
@jdrake89 please schedule

**Comment by jdrake89** [comment]
Meeting set for 4/19/24

**Comment by Reyzerbit** [comment]
@LackyLou @jdrake89 is this resolved after talking to everyone in the meeting?

**Comment by LackyLou** [comment]
> @LackyLou @jdrake89 is this resolved after talking to everyone in the meeting?

As much as it can be

**Comment by Reyzerbit** [comment]
Completed with process change
