### ISSUE TITLE
Feature: Improve/clarify description of fire pit pan + burners.

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#198]
coordinate with MI*

Predesigned A4014-SLCT
D36" x H18"
Material: Aluminum x 0.125
Finish: TBD - Select Powder Coat
Reveal: Skirt x 3" height

**-- Round Firepit Pan (Predesigned 18" Round Fire Pan - 18" Electronic Ignition Round Natural Gas Penta 120VAC (PENTA18EI-NG/120VAC)) x 1**
Addons:
-- 2hr Timer (694) x 1  per unit

**Comment by Reyzerbit** [comment]
Discussed with MI, no further changes needed
