### ISSUE TITLE
Bug: Skirt Logic Flawed?

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#2]
Skirt logic appears to be flawed.

Reveal: None & Skirt should return the same sheet material SF
Skid: should reduce sheet material SF by H" -[Reveal Height"]

**We don't want or need skirt material to account for reveal inset dimensions. When adding 20%yield and having variation in nesting efficiency it's not worth the added complication to account for this.

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
