### ISSUE TITLE
A5004 material showing as .05"

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#200]
<img width="1099" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/85ff1413-1feb-43cf-a5f3-4ad5613720be">

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.27](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.27)
