### ISSUE TITLE
Skirt adding material when 0 is selected

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#201]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/9f2ad9bd-4024-493a-9331-7e079127f644)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/36d72d37-07ad-4219-85ca-48ce82ea3c1c)

**Comment by Reyzerbit** [comment]
This is expected. Skirts have formed inner metal that never disappears even if the height is 0. If you want the reveal to be 0, set the reveal type to none.

**Comment by MattIsrael** [comment]
Are we able to have an input value of 0" change the reveal to None or set it to multiply by 0, equaling 0? 
Any other opportunities to remove this cost adder by only changing 1 variable opposed to 2? 

It's not mission critical, but it would be really helpful.
