### ISSUE TITLE
Feature: Develop York/Sutton ShapeCode

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#203]
Original Title: York/Sutton BOM discussion

BOM items for the York and Sutton are not including all components and quantities correctly.
I spoke with Jake and he would like to develop this so he and Tina do not need to reconcile it later.
I created a calculator for both and can share that for verification and implementation. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/58a9a9d2-0b06-4c93-9003-a0643878f1ce)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e691e496-1841-4ec3-8a4e-57edb6e1a6ea)

**Comment by Reyzerbit** [comment]
@jdrake89 sounds like we need a meeting with necessary stakeholders to develop these shapecodes?

**Comment by jdrake89** [comment]
@Reyzerbit I don't think this needs a meeting, can we change the status. Has estimating provided shape codes?

**Comment by daniel11088** [comment]
we have a calculator for this. I'll send it over.

**Comment by Reyzerbit** [comment]
@daniel11088 please make sure it gets linked back to this github report so i dont lose it

**Comment by daniel11088** [comment]
[Sutton Cornice Calculator.xlsx](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/15266222/Sutton.Cornice.Calculator.xlsx)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.0)
