### ISSUE TITLE
POMO BOM item discrepancy 

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#204]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/0d5dbd73-9cf5-4384-af8b-a48d44b6cf13)

**Comment by daniel11088** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/a07890c1-24e5-462d-b974-5f59142b2d52)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.27](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.27)
