### ISSUE TITLE
Bug: [ORE 3D 2.0] Not able to copy proposal 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#205]
#48386 - Items in proposal not carried over when proposal is copied. Manually copy/paste of items to a new proposal don't save.

**Comment by Reyzerbit** [comment]
Note for self: Line items are being replaced, so throwing error on add lines with existing line number? Try setting line numbers to null

Confirmed this is the issue
Further issue: refactoring duplicate orders method is never being called.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.28](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.28)
