### ISSUE TITLE
Bug: Finish not updating

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#206]
This bug can be recreated on all 2.0 orders.

Finish Issues:
•	Not showing up in description for all products.
       o	 The water bowl shows no finish.
•	Not changing price
•	Unable to change finish more than once.
       o	         Finish sometimes changes in drop down but not updating in description.

**Comment by daniel11088** [comment]
Finish time and BOM item being removed when Art TBD selected

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6ef3e2cb-6f78-48de-8f84-6aa7c740017c)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.28](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.28)
