### ISSUE TITLE
Bug: Pomo Face Qty

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#208]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/62c1651e-7dfc-4dcf-ac91-a455897fa58a)

Both of these should max out at 2. There was the little gray pop-up window at the top of the screen stating the qty had been snapped to 2 (it's maximum value), but the input value didn't change.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.28](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.28)
