### ISSUE TITLE
Abstract description not showing in NetSuite

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#21]
BOM items and notes are not showing up in description.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e8c90cc9-58fc-4b66-ad28-8de38ef7cdb2)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/3372ab15-401d-41db-b4f8-194b5bc8ba8f)

**Comment by daniel11088** [comment]
The description shows up after you save and close the order, reopen it and then refresh the description.

**Comment by daniel11088** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e63d8810-de0f-4bd7-8244-272570fdbcc2)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
