### ISSUE TITLE
Bug: Copy from 1.0 to 2.0 pricing changes (Shipping and Handling)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#210]
Original proposal: 48331
System Information (old total): $75040.35
--Pushed to 2.0: $74693.50

Copy( 48424 in 2.0): $74723.53

Some price changes I can see seem to be shipping and handling. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/7205f1f5-c12e-4e13-8267-ea928697dbd0)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/8c5d6695-b7d1-4a2e-8c56-60b91ed46105)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/ed6a2933-5dfb-4595-ac4c-27536edfb2c0)

**Comment by Reyzerbit** [comment]
Original orders were adjusted, no longer able to reproduce
