### ISSUE TITLE
Feature: Custom Item Not Working Correctly / Fixes

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#212]
Only catagory is finish, need to add all of the options from 1.0 and an "other" catagory for misc items. 

Unit of measure is a massive list and needs to be cut down to remove duplicates. 

Add EACH to list of UOM.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.40](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.40)
