### ISSUE TITLE
Finish Bug still occuring

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#213]
Same issue as before.

In the example below, Cast iron, alloy tier, is selected but is showing Smoked Charcoal, custom tier.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/2ad713d7-78b2-494b-a18a-2189c9093440)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.31](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.31)
