### ISSUE TITLE
Copy from 1 to 2 not showing up in netsuite

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#214]
Copying a 1.0 order in 2.0 does not create an order in NetSuite.

I copied 48470, 1.0, in 2.0 and it generated a copy, 48514.

I can not find 48514 in NetSuite. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/df45153e-640e-482c-a8d5-2b99ae22dce9)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/038a2ca7-3b9b-4554-9240-b93f84ee8e16)

**Comment by Reyzerbit** [comment]
https://3619299.app.netsuite.com/app/accounting/transactions/estimate.nl?id=2455527&whence=

Is this not it?
