### ISSUE TITLE
Fire Feature Issues

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#216]
Fire Feature Issues:
•	Customer facing description not displaying correctly.
•	Changing to a raised lid moves Predesign to Modified.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/11357b01-6cd5-475c-8fe7-a777eb6919c3)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/39df5541-54ef-4e15-bf90-f900f20c0d07)

**Comment by Reyzerbit** [comment]
@daniel11088 checking "raised lid" doesn't make it automatically raised, you have to adjust the height to the correct dimension as well (in this case, 1.3125")

in terms of the description, what exactly is wrong with it?

**Comment by Reyzerbit** [comment]
@jdrake89 request has been made to adjust firepit description, meeting will be needed.

**Comment by jdrake89** [comment]
Meeting set for 4/30/24 - 1:30pm

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.33](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.33)
