### ISSUE TITLE
Bug: Trying to Duplicate empty proposal 48497 from 1.0 to 2.0

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#217]
**Bug:**
Tried loading a proposal using the duplicate button in 2.0 and it has been stuck on this screen with no changes for about 10 minutes.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/1cbf7db9-8bdd-4eb1-a646-1804f08fc39c)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.31](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.31)
