### ISSUE TITLE
Feature: New Shape Codes

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#219]
To include:  4050 / 4051 / 4052

https://docs.google.com/spreadsheets/d/1QAxK2hH6W7wjuHser5Ss9NR2WG09EzBo4548kTCHxfw/edit#gid=0

**Details/Question:**

**Comment by Reyzerbit** [comment]
TARGET COMPLETION PRIOR TO LAUNCH (on/before 5/14)

We need a second finish drop down. 

NPI - bowl and plinth can have different colors with BOM qtys that support that split. 

Price per most expensive finish. 
ex. if plinth is Select and bowl is Art, the pre-designed price should be Art.

**Comment by MattIsrael** [comment]
5004
4050
4051
4052

Please lock out ability to modify for time being. We will develop full shape code logic at a later date. This will get us through the release 5.14

**Comment by jdrake89** [comment]
@MattIsrael @Reyzerbit Please see the google sheet link and update the BOM and Routings, let me know if you have any questions.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.37](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.37)
