### ISSUE TITLE
Incorrect material thickness on S1213

### ISSUE THREAD

**Issue by gg1919** [Ore-Design/Ore3DInternal-Reports-Changelog#22]
See S17540.  The material thickness on the S1213 is 14ga.  It should be 11ga.  This is true for all product that uses the bowl.

**Comment by jdrake89** [comment]
Material in NetSuite assemblies has been updated from 14ga to 11ga per the shop drawings. 

@Reyzerbit Please update in Ore3D 2.0

**Comment by Reyzerbit** [comment]
Fixed in 2.0
