### ISSUE TITLE
6000's series Facade / Surface not showing Drain Hole Option in Description

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#220]
Box is checked but not showing up on description. 

<img width="1108" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/67a4a3d8-6cee-4c51-9776-328320ff603c">

**Comment by jdrake89** [comment]
@Reyzerbit Need to get this one fixed ASAP

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.33](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.33)
