### ISSUE TITLE
Feature: Add "Mouse Hole" option to 4100 Shapecode

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore3DInternal-Reports-Changelog#223]
Grif has requested a discussion about this option. Please schedule a meeting for this @jdrake89 .

**Comment by jdrake89** [comment]
Meeting set for 5/6/24

**Comment by jdrake89** [comment]
@Reyzerbit Decision: Check box for mouse hole that drives to description. On all fire pits.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.34](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.34)
