### ISSUE TITLE
Feature: Add functionality for 2 finishes (Bowl & Plinth)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#224]
TARGET COMPLETION PRIOR TO LAUNCH (on/before 5/14)

We need a second finish drop down. 

NPI - bowl and plinth can have different colors with BOM qtys that support that split. 

Price per most expensive finish. 
ex. if plinth is Select and bowl is Art, the pre-designed price should be Art.

**Comment by Reyzerbit** [comment]
Merged into #219
