### ISSUE TITLE
FUSE split not calculating correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#225]
Same split gives me 2 different prices.

Not calculating section quantity correctly.

Section quantity should be 8 but is only calculating 5.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/f95c7560-2088-4856-b629-6ecea37ae4c4)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/9166209d-f91d-4440-a646-e91045539d8e)

**Comment by daniel11088** [comment]
Split breaks down when width section is increased only on orders that have been copied from 1 to 2.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.33](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.33)
