### ISSUE TITLE
Reopening 48563 caused burner price to disappear 

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#226]
I priced a 4014 in 2.0 yesterday and today the burner price is not being calculated.

NetSuite Sub total - $7,259.00
2.0 Subtotal - $4184.00

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/cfc02fa7-99ec-4f1c-8d84-27d590586da0)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/f31072c5-155c-4489-b78a-c2dbec8f1d0f)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.33](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.33)
