### ISSUE TITLE
How should Discontinued Catalog Products be Handled

### ISSUE THREAD

**Issue by gg1919** [Ore-Design/Ore3DInternal-Reports-Changelog#227]
We had an an issue where a discontinued catalog product was put in as custom which caused the order to unnecessarily be added to CAD's shop drawing queue and an unneeded and incorrect drawing to be created.  I would like discontinued products to be reviewed and ones for which we have received orders on over the last 1-2 years to be added into Ore 3D.

**Comment by jdrake89** [comment]
Meeting set for 5/8/24

**Comment by jdrake89** [comment]
We decided that Estimating has to do better when wirtting up descriptions and information for discontinued standards being sent back through the system. This will be an ongoing issue as we get these types of requests infrequently.
