### ISSUE TITLE
Copy from 1.o to 2.0 issues: Abstract

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#228]
Abstract issues:
Routings not being copied.

Descriptions:

All descriptions, Predesign and FUSE, are "over ridden". (overriden is also spelled wrong in 2.0)
This will be an issue if we are coping from 1.0 to 2.0 and a BOM item does not appear in 2.0.
The description will read the 1.0 version word for word instead of having the BOM items listed.

Not sure what the fix is for this but we need to discuss.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1f95e9fb-be28-4be8-bca7-101334faefdc)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.34](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.34)
