### ISSUE TITLE
All Fire Features add same default burner

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#230]
When adding a pan, the default burner for every fire feature is 351-1007 - 18" EI

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/bd7654e0-f695-4d3d-8feb-76066045d2f0)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.34](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.34)
