### ISSUE TITLE
Orders not saving correctly in 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#232]
I started entering a large FUSE project on 5/7 (48671)

I saved the order after I entered 16 line items to verify it would save correctly without issue.

The order did save correctly over to NetSuite and I printed the proposal.

I reopened the order and entered another 8 line items, 24 total.

After saving again, Netsuite was not being updated and when I opened the order again it had not saved my work. and it some how changed the line items and dollar value in ORE3D.

NetSuite Subtotal - $421,477.83
ORE3D Subtotal - $404,168.62
Saved but did not transfer to NetSuite - $727,336.10

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b24b3f8e-204e-4dc2-82ca-e7f47997c05c)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1ace9e93-f301-44b5-b4e6-4efbaed58537)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/51f1e80d-2980-4bc3-b95d-988f75c1bbec)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.34](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.34)
