### ISSUE TITLE
Bug: [ORE 3D 2.0] Not able to push proposal updates to NetSuite 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#233]
Start
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/b29185db-8d73-4650-9265-f7d33b812a0c)
Update
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/6656bd8d-f1d2-4da5-868f-6803c6fb58fb)
Netsuite proposal after saving update
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/3cb5796b-aa8e-42a0-8950-bfbe5d23be43)
Autosave not working 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/251b8524-6db8-4413-8a70-a9613b6e4a63)
Reopening proposal after updated changes
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/7d5fbc6a-5e41-4665-93fb-491143724612)
All updated data is gone and no way to find it via autosave

**Comment by jjohnson2525** [comment]
Trying the same thing with just custom planters in place of fuse 

Updated data to push to NetSuite
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/ba66e275-bfe3-452c-8585-40be6e1f30ca)
NetSuite after update
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/581411d0-8423-43c8-90c2-2fcd23c1904f)

1 line is successfully pushed to NetSuite. The rest are lost.

**Comment by jjohnson2525** [comment]
Seems to be an issue with the copy line-item feature. When I build planters/fuse planters individually then the data will save. 
Updated data
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/3deb68e7-a8ee-46d3-8c47-8dfa8cda2902)
NetSuite after update
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/9b000d6b-5262-418d-88e5-d90dc0a58ea8)
The data saves successfully, however, autosave still doesn't work.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.35](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.35)
