### ISSUE TITLE
Line item copy issues

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#235]
When we copy a Fire Feature with a burner, the copied item removes the burner price but not description.

The Pan price shows a $0.

The burner price is also not reflected in NetSuite for the copied item but does show in the description.

The burner price appears when the order is reopened in Ore3D.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/953cab79-d202-49b2-a03b-771403c3adcc)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/111027e9-4d50-4385-96e5-d311acf90383)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/7b92670f-04f4-48c7-88e4-9ba49c9f0857)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
