### ISSUE TITLE
Bug: Fuse parent description displaying incorrect information 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#236]
Fuse parent description displaying incorrect information for skid and lip dimension. 
The two fuse children are identical but the skid and lip descriptions are incorrectly displaying as mixed.
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/e47238b8-57db-4e91-ba06-483daeafc9fe)
Additionally, If I copy a fuse child the finish then incorrectly displays as Varies 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/46475591-5268-4084-b4a8-0b0a605dfcff)

**Comment by jjohnson2525** [comment]
The finish with print to NetSuite for the fuse with the two individually created fuse children
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/fef26c9d-dc3c-4a25-8b06-d8013a34e538)
But when I load back into that proposal then the descriptions changes to varies. 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/c1eef023-c31c-473e-8dd8-6ae8429af09a)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
