### ISSUE TITLE
4050 Description Missing Dimensions

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#237]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/7efcec84-7c42-4c01-bf24-731965eae4f5)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
