### ISSUE TITLE
Bug: [ORE 3D 2.0] Standard firepit bug: Using "Match Parent" button on glass surrounds break component cost and pushes firepit into custom

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#238]
On standard firepits, Glass surround "Matches parent" button breaks cost of components. (Requires a pan/burner or lid to be below it) 

Firepit components prior to "matches parent" button being used 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/5d28e30e-831b-457f-8252-e1648294e78a)

Firepit components after "matches parent" button being used
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/e2cd404b-2a06-440c-9b27-a81b7869caba)

Bug doesn't happen if the other components are above glass surround
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/16b3c79a-0000-41af-86ce-65ea78bc9bf5)

**Comment by Reyzerbit** [comment]
This is expected and unavoidable behavior caused by preventing non-catalog products from having catalog children. If you want to avoid having to remove and re-add children, we'll have to address non-catalog having catalog children first.
