### ISSUE TITLE
Bug: 4050 predesign (CT) to predesign (MS) [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#239]
if you switch from the C4050 to the S4050by changing the material and matching the gauge Ore3d does not automatically recognize the S4050 as pre-designed. 

Maybe because there aren't dims yet....

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
