### ISSUE TITLE
LF instead of inches for edging

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#24]
Can we have the parent display in LF instead of inches?

The industry standard is LF so if we could match that it would make it easier for our customers. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/7a3d0f11-b4ed-44de-88ec-d297756f3bba)

**Comment by MattIsrael** [comment]
I agree. Please change UOM of edging parent length to LF.

**Comment by jdrake89** [comment]
This is specific to Fuse Edging only, not for fuse planters. 

For proposal and customer facing Docs - Need LF to match take offs and layout drawings
For SO - Needed for CAD/PM and Production - Ln Inches
For WO - Manual adjustments can be made to accommodate either option. 

If fuse edging - Show LN FT in parenthesis next to inches in description. - IT to program and test in production. 3/7

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
