### ISSUE TITLE
Bug: steel fire pits don't auto select steel lids  [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#240]
REFER TO OTHER BUG - if you switch the material within the child it kicks it to modified 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/66b51f35-2569-430b-9a63-db37e1766ccb)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/4ae81c47-6314-4dd2-89f5-2ba5183d6ae9)

**Comment by Reyzerbit** [comment]
This is expected and unavoidable behavior caused by preventing non-catalog products from having catalog children. If you want to avoid having to remove and re-add children, we'll have to address non-catalog having catalog children first.
