### ISSUE TITLE
4050,4051,4052 Pans need to not have SS in the build. 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#241]
I created these so we can get a burner added to the new product. 

However its automatically putting SS which these builds do not have. 

24-F_PAN-ROUND-BURNER-4050/4052
24-F_PAN-ROUND-BURNER-4051

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
