### ISSUE TITLE
Bug: Fire Feature Burner Selection UI

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#243]
**Bug:**
Can't see what the full burner name is. This causes a problem when trying to select the right burner and fuel type.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/a62804d3-43e5-48aa-9e8f-feb7bb956054)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.36](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.36)
