### ISSUE TITLE
Feature: Base Facade Height 1" Shorter and consider reveal height in calculations

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore3DInternal-Reports-Changelog#248]
**Issue:**
There have been requests to allow for smaller-than-predesigned versions of the cladding planters. Needs discussion with CAD per @jdrake89

**Comment by jdrake89** [comment]
Meeting set for 5/22/24

**Comment by jdrake89** [comment]
Meeting 5/22/24 - @Reyzerbit 
Smaller than standard height:
Based off pre-design and go negative in addition to positive. 
Go through and give shape code full review based on dims. 
Reset min height to 2 rows???
CAD per Grif agrees on custom shorter heights.
Get as close to 12" x 12" x 12" per Matt Israel

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.40](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.40)
