### ISSUE TITLE
Feature: 1 and 3 Sided Facil Facade Option

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#249]
**Issue:**
Hey we have seen a request come through for 3 sided facile façade options. 
we anticipate there being requests for 1 sided as well. 
we would need the option for this in the custom shape codes for the cube/rect Facile Façade shape codes.

Get with Matt Israel for additional information and or questions on this feature request.

**Comment by Reyzerbit** [comment]
Moving assignment to @jdrake89

**Comment by jdrake89** [comment]
Meeting 5/22/24:
Use current shape code to replace Cladding Coverage drop down with 2 number fields, Cladding Long Sides / Cladding Short Sides. 
This allows us to detirmine the sides needing cladding.
Reference pomo shape code for side options. 
This will increase stability of the program in the long term - Jake Batista

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.40](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.40)
