### ISSUE TITLE
Feature: Please show unit price and qty in left side panel 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#250]
Please add unit price and qty to left side panel. Proposal review is not intuitive at this time. 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/f436f466-8cd1-47b2-8a27-2b1198d972de)

**Comment by Reyzerbit** [comment]
This is a planned feature for the summary panel. For now, please right click to view unit price and qty.
