### ISSUE TITLE
Bug: Steel Raised Tops not Pulling into Ore3D2.0[Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#252]
Jake Drake created 12 new BOM assembly items. 9/12 are pulling into 2.0.

Neither Jake nor I can spot what is causing these 3 to not pull into Ore3D.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/4bbbaf32-458e-415e-866f-58ac38e69d1b)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.37](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.37)
