### ISSUE TITLE
Bug: Line item reordering and deleting after save Proposal 48808

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#256]
**Bug:**
Line items were reordered after saving.
I had them in the order that made sense for the customer and it got jumbled after saving.
I also deleted some of my line items i had built in there.

I have no autosave data either to recover lost builds
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/e9f95641-ccdd-4bf1-835e-a04c9d145a0a)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.37](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.37)
