### ISSUE TITLE
Feature: Have fuse routings and material show per each fuse section

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#26]
Current routings show total routings for all sections, I believe. Please adjust this to show just a single section similar to current ORE 3D.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114424580/47549416-d2ea-4330-aceb-509584e56e8b)

**Comment by Reyzerbit** [comment]
Note to Self: Planned feature of the Admin tab.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
