### ISSUE TITLE
Feature: New Bison Shape Code

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#263]
New Bison Shape Code - Discussed with JD 

Bison - 'legacy' build to order items
BisonSTOCK - new shape code. Contains the -FI & -UF part numbers --- Maybe it eventually contains a drop down in the right column to select between UF & FI so the 'add build' list can be shorter, like the Ore products list.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.37](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.37)
