### ISSUE TITLE
Items deleted in NetSuite still show up in ORE3D

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#265]
Jake deleted a Bison product but it is still showing up in ORE3D 2.0

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/2270843f-45cc-4542-abf4-b906da28d975)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/3a4f85fa-b2b6-41ce-abdc-1a740e2bcf76)

**Comment by Reyzerbit** [comment]
Will be fixed with #263
