### ISSUE TITLE
Bug: Standard Fire Features Boms/Children

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#266]
**Bug:**
Adding a Lid to a Steel or Corten Predesigned fire Feature adds in the Aluminum lid and changing it to the right material type kicks it into modified.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/e54a60de-2384-452d-8e74-b7401187fd54)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/ccbaf050-c7fd-4b87-983b-966c307b248a)

Predesigned 4050/4051 Glass Surround has no glass in Bom Item.
Doesn't pull in right material type if steel or Corten. same issue as lids.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/77a7b343-e891-4194-a93a-af17b780e2ae)

Changing Finish of Predesigned lid to Oxidized Zinc Patina from the finish Drop down changes it to modified.
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/c7b2d03f-7952-48ca-8966-69d105036375)

**Comment by Reyzerbit** [comment]
Please see [this comment](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/240#issuecomment-2108295049) on issue #240
