### ISSUE TITLE
Bug: [ORE 3D 2.0] Incorrect pricing on custom fire pits

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#267]
Burner and pan price resetting to $0 after saving and reloading proposal. Bug first occurred when just overwriting description. Also, it looks like the calculation for the pan and lid are reversed.
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/7e1038b6-9a4b-42bc-8e7d-939b959cd899)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/5d3b4ca2-9066-4303-8dbd-4508ec146fa6)

**Comment by jdrake89** [comment]
Adding to meeting set for today at 1:30

**Comment by jdrake89** [comment]
Batista has a fix in progress + Matt I. assembly project.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.45](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.45)
