### ISSUE TITLE
Feature: Pull Bison samples into Ore3D

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#269]
1. Pricing for Bison samples need to be rounded to $0.01 (Official price list attached for referance)
2. Bison samples to be pulled into Ore3D2.0 under SAMPLES category 
[Bison old and new price 4.1.24.xlsx](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/files/15380313/Bison.old.and.new.price.4.1.24.xlsx)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.39](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.39)
