### ISSUE TITLE
Description breaks if no reveal is selected

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#27]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b5b71883-caae-4782-8774-92e37e43e7f9)

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
