### ISSUE TITLE
Sample - Material for .05" is pulling 100-2031 - .50" (1/2). 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#271]
This needs to pull 100-2027 - Aluminum Sheet 5052 4' x 10' x .050" x 1  per unit

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/165270b0-8cac-4e44-a483-73155dc043d3)

**Comment by Reyzerbit** [comment]
Fixed
