### ISSUE TITLE
a6022 - No rail material in BOM

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#272]
I'm assuming this is wide spread to the other 6000 series planters

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/b2a13f72-40c6-47ee-99ea-c6271c5d5d69)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.39](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.39)
