### ISSUE TITLE
Bug: 4040s Wrong Height

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#275]
Can you please change all 4040s in all finishes to 18"H to match NPI sheet and final dims

4043
4044
4045
4046
4047
4048

-SLCT
-ALLY
-PAT
-ART
-ARCH
-RAL
-CUST

**Comment by Reyzerbit** [comment]
@jdrake89 assigning this to you

**Comment by jdrake89** [comment]
Need to check on adjustablity of facil products prior to making changes in NetSuite.

**Comment by Reyzerbit** [comment]
@jdrake89 im gonna go ahead and handle this myself

**Comment by Reyzerbit** [comment]
Done

**Comment by jdrake89** [comment]
Thanks
