### ISSUE TITLE
Feature: Develop Band Shapecode

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#276]
I thought we had a Band shape code developed, but in 2.0 it's producing the same routings as a rectangle of equal dims. 

Design change:
'Groove to have less p-fab  + (1) stitch-weld around perimeter. 

Shape code notes: compared to rectangle
+pre-fab for extra brakes
+fab for (1) full perimeter stitch weld.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.45](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.45)
