### ISSUE TITLE
Discussion: Copy standard products with children changes to modified

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#278]
@jdrake89 
@Reyzerbit

**Comment by jdrake89** [comment]
Meeting set for 5/28/24

**Comment by jdrake89** [comment]
Batista - Pull gaurdrail off of parent, so parent can be modified with predesigned child.
General follow up - Making sure Grif can see what he wants / needs in WO/SO.
Estimating - Be able to copy predesigned configs with children and have it copy exactly.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.45](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.45)
