### ISSUE TITLE
Bug: Formed podium fire pit automatically changes to formed block fire pit 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#279]
The 4052 automatically becomes the 4050 when added
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/646e9966-3cc0-45e5-abbf-d93cf1222269)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/455cdaf7-c870-418b-9cf1-ba893079f47e)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.42](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.42)
