### ISSUE TITLE
Get rid of custom

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#28]
Get rid of custom in the title.
Can't see the full name.
It's fuse and all custom.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/edac60de-b93c-4060-ae81-6d4069f86d83)

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
