### ISSUE TITLE
Bug: duplicate order from 1.0 to 2.0

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#281]
**Bug:**
This proposal was filled with simple custom planters with custom labels and dims, notes. finish Matte Black, 1" lips, 1" Skids, .125" Material Gauge
Tried duplicating an order from proposal 48968 1.0 to 2.0 and got this screen:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/cf4c376e-9a70-49d6-8aea-11e83ba7ca24)

**Comment by Reyzerbit** [comment]
I am unable to replicate this issue. I may have fixed is on accident? Regardless, new proposal number is 48998
