### ISSUE TITLE
Can child finish description match parent?

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#282]
Is it possible to have the drip read the correct finish in the proposal?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/56e8cd68-81e5-47f7-be00-a83b3d7e9a71)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/4126b07f-1aca-4164-8c09-2c76105a327d)

**Comment by Reyzerbit** [comment]
Use the "Matches Parent" checkbox
