### ISSUE TITLE
Bug: [1.0 to 2.0 Copy] Misc. items are removed when proposal is copied from 1.0 to 2.0

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#283]
Misc. charge items are deleted when proposal is copied from 1.0 to 2.0

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.44](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.44)
