### ISSUE TITLE
Bug: [ORE 3D 2.0] Pulls in wrong material for 3/16" AL 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#284]
When material is set to 3/16"AL. ORE 3D 2.0 pulls in [100-2038], which is a "specialty" 3/16" alloy. It should pull in [100-2013] which is our standard 5052 alloy. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/4516ce94-e14c-4202-8aa3-184746d0be81)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/3be478ef-f7f8-48ff-903c-ece8ecc6ce21)

**Comment by Reyzerbit** [comment]
@jdrake89 this is a netsuite data issue, I would like you to handle it so you can better understand how to fix these problems. Let me know if you have questions 😄

**Comment by jdrake89** [comment]
@Reyzerbit This is resolved, material is pulling correctly.
