### ISSUE TITLE
Bug: 2.0 WOs not multiplying element time x line qty

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#286]
Unconfirmed: 
REF: S18128

Micah:
Batista/Israel - can you take a look into A1001 and A1002 (possibly more pre-designs)? These are coming through with 30 and 39 minutes respectively for fab time. 90 minutes is closer to actual time. Seems these may need the ‘standard’ fab time updated to 90 minutes.

MI Response: 
Ore3D is estimating the following fab times:
 
A1001: 119 minutes /ea
A1002: 154 minutes /ea
 
These times are represented within Ore3D and appear to have pushed to NetSuite correctly. Based on what Micah Scott is describing I'm guessing that the time per element is not multiplying by the line quantity.  
 
Something to note is that this proposal & SO was created in Ore3D 2.0. There don't seem to be any problems with the configurations - I suspect the issue lies at/around WO creation. 
 
Jacob Batista Mike Xidis did you guys move the WO link that used to live in the line item on a SO? I don't even see that column, let alone links to the WOs.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.46](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.46)

**Comment by MattIsrael** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/52eced77-0cb2-412b-bdc1-ef05978aad66)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/970313ea-33ba-4003-ab4d-4c4634f7ce73)
