### ISSUE TITLE
Bug: Fire Pits & Components

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#291]
Child (glass surround) material not matching parent at time of ADD.

child only pulls AL assemblies in. 
switching child material to match parent pushes child into Modified.
***child will not be re-recognized as predesigned if you change all fields back to match 'as-added'.***

Child always pulls Select finish in.

**Comment by Reyzerbit** [comment]
Select finish pulling in as default value will always behave that way unless you want to go back to long lists on the "Add Child" dropdown.

Predesigned detection bug will be fixed.

**Comment by MattIsrael** [comment]
if we set 'match parent' as ON by default would that work?

**Comment by Reyzerbit** [comment]
Yeah that'd work

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.47](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.47)
