### ISSUE TITLE
Bug: CT Material Error

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#292]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/7f9e4339-3337-40cd-b836-49ecfa43314a)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/7c0d89ce-a8b8-4499-b32b-2bbc70560ddc)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.47](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.47)
