### ISSUE TITLE
Feature: Can't read burner descriptions in drop down.

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#293]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/076c9473-a546-43e3-a6a8-5a19e94e107e)

Can't read fuel or burner description.

**Comment by Reyzerbit** [comment]
Same issue as #350 , will look at a solution for both

**Comment by MattIsrael** [comment]
@Reyzerbit  This is still an active bug. Please reopen and provide an update on #350 or this one? It's pretty impactful, especially when new estimators.

![image](https://github.com/user-attachments/assets/6e47e8b8-087f-4f54-ba66-4e292a321b98)
