### ISSUE TITLE
[ORE 3D 2.0]  - Price for custom pan not being added to custom firepits

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#295]
When pricing a custom firepit, the cost of the custom pan is not added to the total price
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/fee94945-3e5e-4cfc-abbc-eebcf4b6f21a)

**Comment by jjohnson2525** [comment]
The above is a modification using the linear firepit shape code. For some reason, it seems to still recognize the custom 61"x8" fire pit pan as a standard item. This remains true if I match the pan dims to the burner dims, however, if I make the pan a different dimension from the burner, it adds in the routings and material. Also, FAB time on pans looks to be calculating incorrectly. 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/964e2ca9-a618-470d-8f2d-e59705d0f5ae)

When using the Rectangle firepit shape code, It correctly recognizes it as a custom item, but doesn't calculate any material. Once again, this is fixed if I don't match the burner and pan dims.  
Matching pan and burner 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/d97d1417-417b-4d53-b7e0-86bf59cd56ad)
pan and burner with different dims 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/ab104d37-1324-4d75-a8c2-27b15b54f65a)

**Comment by Reyzerbit** [comment]
This is expected behavior. Please discuss with @jdrake89 if you have questions.
