### ISSUE TITLE
Bug: NPI Fire Feature BOMS not accurate

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#298]
**Bug:**
MI said this issue was already noted, I couldn't find the bug so I'm making this bug report just in case.
BOMs in 4050 Formed block are wrong, they are adding and extra few hundred dollars of material and don't match the NPI Spreadsheet with the actual BOM QTY
They are adding extra yield on top of yield already calculated during the development process.
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/0d548306-57b6-44df-9775-5622776175d2)
It also shouldn't be doing decimal places for the formed top BOM item, it is a whole integer BOM type only

**Comment by Reyzerbit** [comment]
Verified with Beau, sheet metal amounts are correct. Will adjust the 100-3041 and related parts to correct value.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.48](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.48)
