### ISSUE TITLE
Bug: Material + Finishes

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#3]
1. Allows for selection of irrational material + material gauge (.090" Mild Steel - doesn't exist)
2. Oxidized Zinc Patina not valid finish on Mild Steel or Corten (only on aluminum)
3. 304 Stainless increases Fab time - it should not
4. A[model#] pre-designed elements allow you to change the material, but doesn't change the 'A' in the model # 
5. per above, finish doesn't change finish suffix on model #

REF: Line 4
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/24ea205b-a700-4ede-8a88-1b71be31381e)

**Comment by Reyzerbit** [comment]
@MattIsrael once you return on Wednesday, please clarify item 3. In 1.0 you told me to increase fab time if material is stainless steel based on a modifier we called the "tig weld" mod. Does this no longer stand in Ore3D 2.0?

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
