### ISSUE TITLE
FUSE description not reading correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#30]
FUSE parent description reads Mixed x Mixed when none is selected for all children

Can we get the same description layout as ORE3D-1?

MI approved.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/b5a3c770-7906-4dde-8017-c9d2fe9c7e23)

**Comment by Reyzerbit** [comment]
@daniel11088 I am unable to replicate this. Please come talk to me when you have the chance.

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
