### ISSUE TITLE
Feature: [ORE 3D 2.0] - "[Custom BOM]" prints to proposal

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#300]
When creating a Custom BOM item, the auto-generated "[Custom BOM]" gets added to the description. Will you stop this note from getting added to the proposal description? 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/2b54ed05-f9a5-4b58-a436-742b08654962)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.2)
