### ISSUE TITLE
S18090 - Drip tray QTY's were incorrect when WO's were created. 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#301]
QTY of line item did not multiply the QTY of drip trays. 

Not sure if this is a system or skill issue.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.48](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.48)
