### ISSUE TITLE
Bug: Ore3D Times Not Pushing to NetSuite line item - WOs ok

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#302]
_Follow-up with Lacey if needed. 
_
S18144 - Line 1:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/1f9743e3-b390-4f00-a809-1092b95155c0)

WO31334:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/4a75770f-c553-4bec-bb65-adfb491c2043)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.48](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.48)
