### ISSUE TITLE
Bug: Bug #286 Not Resolved [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#303]
https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/286

**Comment by mxidis** [comment]
The issue is that Sales Order (and Proposal) line items are showing the per/qty time, rather than the whole time for the line.  WO generation is functioning as intended. 

@Reyzerbit, please update Ore3D to put whole line times (piece time * qty) on transactions

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.50](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.50)
