### ISSUE TITLE
A3002 Gallery Bench Fabrication Time inaccurate: Fabrication Time is Off Ore3D 1.9.29

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#304]
**Bug:**
A3002 Gallery Bench is coming through Ore3D with 75 minutes per piece when it should be closer to 290 minutes. 

**Recreate:**
1. Load order S18190 Fabrication Time

**Additional Context/Questions:**
I have a spreadsheet with times for all benches from completed work orders if you need the time to be confirmed.

**Comment by Reyzerbit** [comment]
Issue is 1.0 only. Because 1.0 is being phased out, please convert to 2.0 where possible, but otherwise this will be resolved in 2.0 only.
