### ISSUE TITLE
Bug: [2.0] ORE 3D crashes when changing material on fire pits

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#305]
When I try to change the material from Aluminum to Mild Steel I get an error and ORE-3D crashes
Aluminum
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/a771d8f6-6184-407f-980e-7f25ae678c02)
Mild Steel 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/5c8d37e7-42b9-4aaa-b7b5-d407fe6f4815)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.50](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.50)
