### ISSUE TITLE
Bug: [2.0] Fuse misc charge description not printing 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#306]
When adding a Misc charge to a fuse child, the child description is not printed to the parent description. 

MIsc charges
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/5a1ae507-812e-4955-a15b-3a35be5d3fbd)

The display to description is checked but I'm not able to modify it. 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/a68e3a9e-0307-4f4b-ac6b-7e553eb4ef61)

Doesn't show up in parent description 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/a5df3521-5077-4cab-9a85-e30793eeef2d)

Doesn't print to NetSuite
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/8622751b-669e-46b1-bbf4-a96315132f8a)

**Comment by Reyzerbit** [comment]
@jdrake89 this is a functionality change that _probably_ needs a meeting, what are your thoughts?

**Comment by jdrake89** [comment]
Meeting set for 6/21/24

**Comment by jdrake89** [comment]
@Reyzerbit  Meeting descision - Charges should show up on parent discription. 

Bug submital is accurate please fix.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.52](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.52)
