### ISSUE TITLE
Bug: Custom Fire Feature Children Shape Code Review

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#307]
**Bug:**
Refer to bug #156 for shape code formula from MI.

Ore3D 2.0 is Clearly not following the math for the custom children in fire features 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/a900e696-ffb2-40b6-9de1-4233702107a5)
what the formula should be pulling in FAB minutes:
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/ad9b7d33-45b6-46d2-9de8-f67ee3a7aa07)

Discuss with Matt Israel if anything is unclear

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.50](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.50)
