### ISSUE TITLE
Copy from 1 to 2 issue

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#308]
Fuse Fitup routings are being added when coping 1.0 to 2.0

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/307e530d-8064-4712-ac25-07c9a7862f2d)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/77b47b39-b701-4261-9c3c-43929a025275)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.50](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.50)
