### ISSUE TITLE
Create Custom Component Issues

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#309]
•	Description is no longer an option in 2.0
      o        We need the description to be add in the vender quote number for Jake
•	The add to build button is not adding component to build
      o	If we leave the build and come back it will appear
•	Customer facing description is labeled as - [CUSTOM BOM] 
      o	 Can this be removed?

**Comment by daniel11088** [comment]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1d30f7c5-9f82-445e-8988-6f741290451e)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.50](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.50)
