### ISSUE TITLE
Bug: Custom Component Burner

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#312]
**Bug:**
Dimensions don't hold input number for Burner Length and width inputs. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/b0ba8c29-2a72-40a5-b736-b6dba5885d68)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/6aec3fcc-44cd-4194-bca5-21dca697457a)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.52](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.52)
