### ISSUE TITLE
Bug: Predesigned 5003 Missing Bowl BOM 

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#313]
The A5003 is missing the Bowl BOM Item in the List of materials. 
2.0 is pulling in an error that the bowl size isn't found and it's missing the comoponent
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/dde98f87-4e6b-41c6-8a79-742c694662a9)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/eefa17c1-c624-4bbc-ab56-0264534814ff)

**Comment by CBarsell** [comment]
JD double checked all components that need a bowl are having the same issue

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.52](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.52)
