### ISSUE TITLE
Bug: Bison shape codes locked out in 2.0 - unable to add/create modified bison

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#314]
unlock bison shape codes in 2.0 
(leave 'stock' items as locked)

**Comment by Reyzerbit** [comment]
@jdrake89 this is in direct conflict of what you previously requested. Is this something we need a meeting for, or do you plan on talking this out with @MattIsrael?

**Comment by MattIsrael** [comment]
@Jake ***@***.***> - maybe miscommunication re: the ‘Stock’ bison items vs their standards??

Happy to talk and figure out where it makes the most sense to add this functionality.

@Jacob ***@***.***> thanks for IDing the conflict!

[Ore Logo]
Matt Israel
Estimating Manager

***@***.******@***.***>
→ 385.249.1980

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>

**Comment by jdrake89** [comment]
@Reyzerbit @MattIsrael Let's chat RQ on this, should be easy to get a solution.

**Comment by jdrake89** [comment]
@Reyzerbit @Reyzerbit Batista and I spoke about this and agreed to reopen Bison items to be customized. I couldn't remember what the reason behind closing them off was.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
