### ISSUE TITLE
Custom Components not coping from 1.0 to 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#315]
Custom Components not coping from 1.0 to 2.0 and are unsearchable in BOM.

Additionally, the description will read that custom BOM item is included instead of reading what is listed in the BOM.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/71995560-bd5e-4926-969a-eecce481551b)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/d910a3c4-7709-44f6-b6e6-32f80edca80b)

**Comment by Reyzerbit** [comment]
Issue was invalid unicode characters in display name
