### ISSUE TITLE
Bug: Weight Calculations Lagging

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#316]
I verified with Jake that the weight is set up correctly in Netsuite.

2.0 calculating .375 as weighing less then .25 even though it shows heavier in Netsuite.

.375 in Netsuite is 5.5 lb sqft
.25 in Netsuite is 3.62 lb sqft

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/afc5ca93-27d4-4ca7-b99d-73c7392d9ad1)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/6872258d-e0c4-4dbd-9bc7-6968986e6c8d)

**Comment by daniel11088** [comment]
laggy weight

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
