### ISSUE TITLE
"Copied From" field

### ISSUE THREAD

**Issue by mxidis** [Ore-Design/Ore3DInternal-Reports-Changelog#317]
Add a Copied From field to Transactions that Ore3D works with.  When someone uses the copy transaction function, fill in that field with the transaction from which it was copied.

**Comment by mxidis** [comment]
in 1.0 and 2.0

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
