### ISSUE TITLE
Bug: Standard (no Drain Holes)

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#319]
**Bug:**
Selecting no drain holes option box on a standard planter build changes it to custom.
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/5edc2589-8c8f-4b08-bf05-5997473f39e3)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/11a6d563-8b41-45ac-a987-170ad7f5c7c9)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
