### ISSUE TITLE
Display in Description button broken

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#32]
Display button for Misc Charge not working. 

Misc charge shows up on proposal regardless if button is selected or not.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/d03fdad2-36b5-44ba-b60f-cb8b1b55ae05)

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
