### ISSUE TITLE
FUSE Curved Edging Pre-Fab over calculating

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#320]
1.0
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/f1463065-3ad0-4826-8e86-084c4f92be44)

2.0
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/300147c4-b731-40fa-8698-7cfc1b2a3d33)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
