### ISSUE TITLE
Bug: Shipping Rate Doesn't Recalc on proposal save in 2.0

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#323]
The shipping rate doesn't auto update when the Ore3D proposal is saved. I had to edit the proposal and recalc shipping manually.

**Comment by Reyzerbit** [comment]
Hey @MattIsrael, I am unable to replicate this. Do you have a specific proposal that is having this issue that I can look at?

**Comment by MattIsrael** [comment]
I should have given you that, huh. Disregard if you can't recreate it. I'll let you know if I see it again and I'll be sure to give you the proposal #.
