### ISSUE TITLE
Bug: Ore3D Price Rounding Anomaly

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#324]
Price rounding appears to differ between UI and Ore3D. Unable to use Misc charge to adjust price on item with qty to hit even dollar amount. 

qty - $ rounds down.
when qty is added it creates a delta that is >$0.01

![image](https://github.com/user-attachments/assets/f507144b-dde5-4c9e-bb33-ec5effe84a54)
![image](https://github.com/user-attachments/assets/16a3d98b-a094-46e7-abce-2e2fd0deca05)
![image](https://github.com/user-attachments/assets/f352af78-a510-4b8e-a3e2-05611bf4390f)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
