### ISSUE TITLE
Feature: Price Override functionality

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#325]
**Issue:**
behavior of price override does not behave in a manner that is beneficial to workflow. 
It's not intuitive behavior change from how 1.0 acted with price over rides. 
Using Misc charge can easily get unwieldy when doing overrides on something like fuse.
Reference Bug #324
Also can't hide misc charge if needed without overriding description.
We need a way to do a flat rate that won't have a rounding error and doesn't cause issues with our product description
![image](https://github.com/user-attachments/assets/468b6110-c989-4df8-8fe0-a9955cea7240)

**Comment by Reyzerbit** [comment]
Merged with #324
