### ISSUE TITLE
Feature: Customer Notes in Fuse Children

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#326]
Would be very nice if the Customer Notes in Fuse children would roll up to the parent. 

This would eliminate the risk of putting a note in the child by accident and have it not be visible. 
Also allows to better organize notes if they can be paired with the corresponding child.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.2)
