### ISSUE TITLE
Bug: Misc Charge Issues 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#327]
REF: 49924

Misc charges added to fuse parent add $, but the description doesn't show. 

Also, the Display in Description check box is grayed out. This is the case for misc charges in the child and parent. 

![image](https://github.com/user-attachments/assets/eb77ce47-2d7d-4a52-a2c4-95d17a8c85ee)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.0)
