### ISSUE TITLE
Opening orders from previous versions change standards to custom

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#329]
![image](https://github.com/user-attachments/assets/c61b6e86-ab86-46d2-b9dc-887531957470)

![image](https://github.com/user-attachments/assets/22565c3d-c9d2-4c4c-b737-fcb4387605b0)

**Comment by Reyzerbit** [comment]
This is all expected due to changes in Ore3D behavior. A combination of updated values from NetSuite, and new shapecode changes.
