### ISSUE TITLE
Oxidized Zinc Patina finish time is higher in 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#33]
Not sure if 1.0 or 2.0 is wrong but the finish time in 2.0 is nearly twice as much long.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/ea8583c8-3e75-42cc-b200-7a21af9c4f5d)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/7b39b8e0-fc57-4f67-b2d2-0987a61c69b8)

**Comment by Reyzerbit** [comment]
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)
