### ISSUE TITLE
Bug: BOM/Routing/Misc number de-syncing on change

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#330]
Negative/Positive misc charges no calculating.

![image](https://github.com/user-attachments/assets/83db7490-49e7-4612-bb4f-41fac2c8d72e)

![image](https://github.com/user-attachments/assets/cc2e09d9-219a-4e25-b165-4ab780fb47db)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.1](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.1)
