### ISSUE TITLE
Feature: Option to Manually Kick Build to Custom

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#331]
Original Title: Adding Non-standard burner to Standard Fire Feature - kick to modified [49966]

**Bug:**
I added a push button ignition to a 4050 and anything with a push button burner is modified.
2.0 did not kick the fire feature to modified when adding the non-standard burner

temporary fix was to change the description to modified so it hopefully gets kicked to PMs as a custom item.

We need some way to either push a button that makes ore3d no longer identify a build as standard or a way for fire features to be kicked to modified when adding a non-standard burner.
![image](https://github.com/user-attachments/assets/c19f338b-178c-4360-a430-64201adb9258)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.1](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.1)
