### ISSUE TITLE
To Discuss: Adding BOM/Routing/Misc to Fuse Parent causes weird behavior

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#332]
![image](https://github.com/user-attachments/assets/9696fd91-ad1b-459b-aa27-f6755e2ef677)

![image](https://github.com/user-attachments/assets/22e83b1c-f96c-4862-a750-4b6188aeb661)

**Comment by Reyzerbit** [comment]
BOM/Routing/Misc charges shouldn't be added to Fuse Parents. Want to discuss disabling adding these options to Fuse Parents at all.

**Comment by Reyzerbit** [comment]
@jdrake89 @OreController do you think we need to have a meeting regarding being able to add Misc Charges/BOM Componenets/Routing Steps to Fuse Parents, or do you two have an executive decision regarding this?

**Comment by OreController** [comment]
I think it's probably best if we have a meeting on this.  I'd like to understand this better before making a call.

**Comment by Reyzerbit** [comment]
@jdrake89 @OreController when are we scheduling this meeting?

**Comment by jdrake89** [comment]
My bad, meeting set for Wednesday 8/14/24
