### ISSUE TITLE
Bug: Estimated Fab Time on the SO Line Item Not Matching Time on the Routings in Ore3D [Ore3D Version (2.2.1)]

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#334]
**Bug:**
S18312 has 30 minutes of estimated fab time listed on the line item in NS. In Ore3D is has 171.5 minutes for fab listed for each piece. There is fab routing that was added to the order that is a total of 30 minutes so it looks like maybe NS is taking that overridden amount rather than adding it to the total for the fab minutes. 

**Recreate:**
1. Load order 'S18312'
2. Scroll down to Line Item # 1 and scroll over to the EST FAB TIME (MIN) column to see the number in NetSuite. 

**Expected Behavior:**
The line item estimated fab time in NetSuite should = Ore3D estimated fab time (all fab minutes combined) x quantity of items being built for that item. 

**Additional Context/Questions:**
![image](https://github.com/user-attachments/assets/aa245e43-6efb-4114-8f68-f91c232e0838)
![image](https://github.com/user-attachments/assets/c02cdf78-48e8-43a1-92c1-596b3688b47a)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.3](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.3)
