### ISSUE TITLE
Feature: Round OR Square Pan for Fire Features

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#335]
**Issue:**
Need an option to push a round fire feature pan and burner in a square body and vise versa.
![image](https://github.com/user-attachments/assets/cbda4877-05a2-4aba-aece-82ae36fd9aa3)

**Comment by Reyzerbit** [comment]
@jdrake89 this fundamentally changes the way firepit shapecodes work, I think we're going to need to talk about this

**Comment by jdrake89** [comment]
Meeting set up for 7/31/24

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.4)
