### ISSUE TITLE
Feature: Square Fire Feature missing Reveal Options

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#336]
**Bug:**
Custom Square Fire Pit is missing the option to adjust the reveal height. 
![image](https://github.com/user-attachments/assets/f87f1865-a335-4347-9da7-bc4a9d6e0c9b)
that is a thing we need to adjust at times for a custom request from a customer

**Comment by Reyzerbit** [comment]
@jdrake89 @OreController making this change is tricky, as the square firepit doesn't follow the same calculations for reveal as other products do. The Square Firepit reveal is the stilts, meaning that we will most likely need to develop separate calculations for it as it is so unique. Im not sure if you would like to discuss what this process would look like, or if you just want me to handle it? Changes to the shapecode also mean that old orders with this shapecode in it become, for lack of a better word, obsolete. I want to make sure we make this change as smoothly as possible, so when you two are free, can we have a chat about this?

**Comment by OreController** [comment]
Not a fan of breaking orders in process… let’s talk about this more.

[Ore Logo]
Tyler Gephart
Assistant Controller

***@***.******@***.***>
→ 801.677.0359

**Comment by Reyzerbit** [comment]
@OreController @jdrake89 meeting for this?

**Comment by jdrake89** [comment]
Meeting set for 8/14/24

**Comment by MattIsrael** [comment]
> Meeting set for 8/14/24

Please cancel meeting - talked to Chis and it sounds like a communication error (square vs block/rectangle). 

Ore3D has the necessary functionality where needed.
