### ISSUE TITLE
Bug: Proposal details for Fuse not Displaying Weight

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#337]
**Bug:**
Proposal 50086
The Weight Column in the printed Proposal is not showing actual weights for Fuse Edging Items.
![image](https://github.com/user-attachments/assets/35d3180a-5647-49c3-b310-4e1cbb142b22)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.4)
