### ISSUE TITLE
Bug: Water Bowl Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#339]
Waterbowl (5003) description incomplete. please match description contents and formatting of 1110 or other pre-design element. 

![image](https://github.com/user-attachments/assets/4d09a16f-e787-4a5b-8886-d17037308c18)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.4)
