### ISSUE TITLE
Can we get total routings in FUSE parent

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#34]
Can we get the routings totaled up in the parent view like in 1.0?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/c4819676-4d55-40e5-98ed-69d0a507acfa)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/39cb7596-e828-47d8-ac6a-2ab990b096bb)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
