### ISSUE TITLE
Feature: Custom Surface Height Snap

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#340]
When customizing height on 6082:
Reduce accuracy to ~3 decimal places (1/8")?

![image](https://github.com/user-attachments/assets/ef26de8b-5444-40c6-909f-5887b9c5641e)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.1.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.1.4)
