### ISSUE TITLE
Bug: Price not matching in Ore3D 2.0 and Netsuite Proposal 50047

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#344]
**Bug:**

Netsuite Price: 
![image](https://github.com/user-attachments/assets/83a8557f-e6db-45d2-af4c-af1aac13b2a9)

Ore3D Price: 

![image](https://github.com/user-attachments/assets/de53cb87-a6dd-4274-8768-ffb776adbaa6)

Need to get this fixed ASAP!!!

**Comment by OreController** [comment]
That's pretty extreme, let's get this fixed.  What's causing this?  Looks like it's not loving abstract items.

**Comment by Reyzerbit** [comment]
Unable to replicate now that data was overridden.
