### ISSUE TITLE
Feature: Change Height to always be last in Ore3D input fields

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#345]
Please change cylinder (and other shape codes if needed) to have HEIGHT be last in list of input dimensions. Continuity. 

Rectangle:
![image](https://github.com/user-attachments/assets/058f8ab8-1b70-4915-8273-a5560e919301)

Cylinder: 
![image](https://github.com/user-attachments/assets/76d54818-cb73-411d-b394-77e9c91c2583)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.0)
