### ISSUE TITLE
Netsuite: Missing Weights for Corten

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#349]
Original Title: Bug: Curved Edging Weight Calc

**Bug:****
Corten Material in a Curved Edging, and straight Edging condition isn't calculating piece weight.

This is very important as Weight is our biggest restriction when it comes to calculating piece sizes in Corten due to how heavy it is.
![image](https://github.com/user-attachments/assets/d8468b2a-edfb-4723-b7b5-d9912957ddc7)
![image](https://github.com/user-attachments/assets/8a01abe7-1a1a-412a-98b8-0a79d7309b62)

**Comment by Reyzerbit** [comment]
@jdrake89 looked into this, it looks like some of our sheet metals don't have weights associated with them. I'm assigning this to you as you are in charge of handling weights in NetSuite. Feel free to close this issue once you've added weights to missing sheet metals (currently 104-2017 is missing weight, not sure what else is)

**Comment by jdrake89** [comment]
I'll ask Mike for a saved search to get this done.

**Comment by Reyzerbit** [comment]
Completed
