### ISSUE TITLE
Bug: Descriptions Are Being Overridden when Converting from 1.0 to 2.0

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#351]
Applies to custom and standard items. 

Upon proposal save & reopen ALL line items have their description 'overriden' without user manually editing the description.
![image](https://github.com/user-attachments/assets/790e3377-fbe7-4483-a031-bae876bdd587)

**Comment by Reyzerbit** [comment]
@MattIsrael i am unable to replicate this on my own. Do you have a specific proposal this is happening to? Or is this happening to all of them?

**Comment by MattIsrael** [comment]
S18498 / 50195

**Comment by Reyzerbit** [comment]
Talked to Matt, issue is do to 1.0 to 2.0 conversions and is unavoidable. Current course of action is to encourage checking your descriptions thoroughly, regardless of department. @OreController we may want to consider a training for this?

**Comment by OreController** [comment]
I don't understand, if you're locked out of editing the description, how would checking it thoroughly help?  Is the concern that CAD might not notice something?

**Comment by Reyzerbit** [comment]
@MattIsrael @OreController i was told you guys had a conversation about this, any decisions made?

**Comment by OreController** [comment]
Israel and I talked about this yesterday, I believe a couple of things should be done.  It'll probably be a good idea to have you (Batista) give a training to the BDs on this and other common issues they'll just need to be on the lookout for.

I also think we might be able to come up with saved searches or flags of some kind help us with possible data integrity issues, we can discuss this in further detail later.  For example, an easy search would be IT gets an email from NS every time someone saves a proposal that isn't in the newest version of Ore3D (I understand that's a separate issue but it illustrates the point).  Another example could be when certain parts of a build don't match the BOM, a reminder is triggered.
