### ISSUE TITLE
Bug: Netsuite Description 

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#353]
**Bug:**
Proposal is Printing out "Custom Fuse Parent" in the description under the name.

It shouldn't say Parent at all in the description. It is a planter so it needs to say planter if it is going to be listed twice.

![image](https://github.com/user-attachments/assets/6eaa013d-b0a7-4d58-9160-986b6c180ab5)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.5](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.5)
