### ISSUE TITLE
Bug: Saving "Cancelled" error 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#354]
Data is saved to NetSuite but ORE 3D shows as cancelled 
![image](https://github.com/user-attachments/assets/e58b93ab-869d-42f1-a64a-c024198024d8)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.0)
