### ISSUE TITLE
Bug: Ignore Predesigned button broken

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#355]
**Bug:**
As Discussed

check box overrides predesign as intended but after a save cycle the proposal will show the item as predesigned again. 
It does not retain the price change of changing something to custom.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.2.6](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.2.6)
