### ISSUE TITLE
Bug: Cannot Copy Proposal [if not active BD?]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#356]
Ore3D NOT ABLE TO COPY PROPOSAL (REF: 49182)

Disregard if this is not 'real' (this is hear-say)
Ore3D will not allow you to copy (maybe other functions as well) a proposal if the Sales Rep(BD) is not 'active' (per Josh - not sure what that means).

Proposals need to be able to be copied regardless of who the Sales Rep or Estimator are. 

We need to be able to maintain historical records accurate, especially in the context of former employees. Records such as who received the RFQ, who was potentially on the phone discussing a proposal and whos email we may have to dig through in the event we need to answer a question.

**Comment by Reyzerbit** [comment]
Would it be possible for you to create a test proposal with no sales rep/estimator so I can test this?

**Comment by MattIsrael** [comment]
@Reyzerbit please re-open per conversation with MX and @OreController.
