### ISSUE TITLE
Bug: NetSuite Shipping, Handling & Tax NOT Auto-Updating

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#357]
REF Proposal: 50242
Submitted on behalf of Geoff Conner

User has to manually 'edit' the netsuite record and recalc (recalculate shipping) 

*I haven't personally seen this.

**Comment by Reyzerbit** [comment]
After Research:
Some proposals/sales orders save to NetSuite, but during the post-save process, an error occurs NetSuite side (internal NetSuite code, out of our control). This causes Ore3D to believe an issue has occurred even though the save cycle completed successfully. This causes Ore3D to skip the shipping/tax recalc step.

Current planned resolution is a detection system to determine successfully saved records even when save cycle returns 500.

**Comment by Reyzerbit** [comment]
This is related to #354

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.0)
