### ISSUE TITLE
Bug: BOM Item Margin opening 1.0 order in 2.0

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#358]
REF: 48371 (line Ore-Design/Ore-3D-Reports-Changelog#2, child Ore-Design/Ore-3D-Reports-Changelog#1)

This is a 1.0 proposal, when opened in 2.0 (open locked). the BOM options, specifically BB-AL is pulling in with margin. This item is not supposed to have margin added to it per it's netsuite settings. 

if I add BB-AL to a new 2.0 proposal it pulls in with no margin - correct. 

Maybe this is just a product of opening a 1.0 proposal in 2.0 in the 'open-locked' mode?? I wasn't able to test further. When I tried to let Ore3D 'Duplicate Order' and convert it to 2.0 the line items failed.

1.0
![image](https://github.com/user-attachments/assets/30c3ad30-bb04-4efc-836b-0dfefae683f4)

2.0
![image](https://github.com/user-attachments/assets/e337615b-37e8-4137-8709-4f969f784444)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.0)
