### ISSUE TITLE
Adding a skid adds roughly 20% to sheet metal

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#36]
This occurs on all planters. FUSE and Non-Fuse

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/265f4bba-0644-45b3-bb90-a570cc27e2ee)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e99919fc-f48d-4c5d-a8aa-27f7544c79e7)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/25015fc8-4b21-4710-8773-d3a18da2adbf)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/a6a6b4f6-3fb7-4d7f-9a15-2ac21d3c3f3e)

**Comment by Reyzerbit** [comment]
Completed in [1.0.11](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.11)
