### ISSUE TITLE
Bug: Custom Fire Pit Pan: H-Burners

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#365]
When a H-Burner is added to a custom pan ORE3D correctly removes the stainless material, **it does not remove routing times.

IF H-BURNER: ALL ROUTINGS = 0**

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
