### ISSUE TITLE
Bug: Water Bowl Missing Routings

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#367]
**Bug:**
A5003 is missing all routings.

Lacey is unsure if she will be able to create a WO without any routings in there 
![image](https://github.com/user-attachments/assets/a4befbc3-28e3-4231-97f3-644701309295)

**Comment by mxidis** [comment]
Directed Chris to just add 0-Minute routings for each step for now.

**Comment by Reyzerbit** [comment]
@OreController @jdrake89 I have no routing data for water bowls. No effort was ever made to determine these routing values due to how few of these we sell. Should something be assigned to make these routings happen, or should the process simply be 0/1 minute routings?

**Comment by OreController** [comment]
Can we schedule some time to go over this one as well?

[Ore Logo]
Tyler Gephart
Assistant Controller

***@***.******@***.***>
→ 801.677.0359

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
