### ISSUE TITLE
Bug: Fuse Planter Split: Qty produces different material SF than split

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#369]
SOMETHING TO DO WITH THE SKIRT CALC
These configurations with a 1" skid match (correct).

Fuse child with qty produces different material SF and finishing (driven by SF) than a split configuration. 

Child qty (1) x section qty (5) = 5 sections
![image](https://github.com/user-attachments/assets/9010fb48-1ea8-411b-b424-6253adc630b8)

Child qty (5) x section qty (1) = 5 sections
![image](https://github.com/user-attachments/assets/df342ce2-014d-4806-94eb-44f3e2c7ea36)

contact Matt I & Chris B for more info.

**Comment by Reyzerbit** [comment]
@MattIsrael I am unable to replicate this. Can you please provide some more detail to this? I have set two separate rectangular fuse planters to the same values, including 1" skid, and one is set to 300"x24"x24" with 5 piece split, while the other is set to 60"x24"x24" and no split. Price, SqFt of sheet metal, and routing times all match. Is there another field that I'm missing that is affecting this?

**Comment by Reyzerbit** [comment]
Talked to MI and discovered issue, will be resolved in next release.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
