### ISSUE TITLE
Feature: Bison Trays Description

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#372]
**Issue:**

Bison Trays do not need a logo or Irrigation tube. 
this needs to be removed from default description for trays.
and the default build need to have the BOM item removed for the tube.

![image](https://github.com/user-attachments/assets/0adc629e-4790-4832-be30-b1b45134b02f)

![image](https://github.com/user-attachments/assets/182a80d5-e990-48eb-ae94-bf32c39c6d26)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
