### ISSUE TITLE
Bug: Proposal 48548 to S18605 Price change

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#373]
**Bug:**
Proposal 48548 has a Subtotal of $6,412.77 Total of $7,303.42
Sales Order S18605 subtotal of $6,308.94 total of $7,185.05
![image](https://github.com/user-attachments/assets/8de89592-aebd-449a-99af-bdc8dd920a94)
Total and subtotal changed when it was processed into a Sales order.
Proposal Time stamp: 
![image](https://github.com/user-attachments/assets/3175b1a9-c7d1-48bf-94d0-3379aa108f10)
S18605 Time stamp:
![image](https://github.com/user-attachments/assets/b2d697ec-cc56-4c0e-ad35-7b9961d3c12c)

I kept going with the sales order to update price so Don't look at anything in system info after 10:45AM 9.9.24

Looks like BOM item 351-1241 is the only thing that changed in Ore3D from proposal to sales order

**Comment by Reyzerbit** [comment]
I am unable to replicate this. You may just need to re-save the sales order, because when I open S18605 I see a much less drastic change in price.

**Comment by Reyzerbit** [comment]
Most of this can be chalked up to expiration/outdated information. Proposal 48548 was expired at time of conversion to sales order, which means that pricing/logic can change.

**Comment by CBarsell** [comment]
I updated the SO for the price to be accurate cause we have to send it. I did say not to look at the change logs after about 10:45am in my bug report.

**Comment by Reyzerbit** [comment]
As a general rule of thumb, if an issue is found with a SO/proposal, please avoid making any changes to the order until I can take a look at it, otherwise I will be unable to resolve the issue. Glad a workaround was found 😄
