### ISSUE TITLE
Bug: ORE 3D 2.0 - Custom glass surround not pricing 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#374]
Looks like the glass surround calculator is broken for custom fire features
![image](https://github.com/user-attachments/assets/958d0f29-3077-4167-99bf-57141a18c45c)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
