### ISSUE TITLE
Bug: Fuse section count not correct when splitting width and publishing to NetSuite 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#375]
Reference proposal #50654
Should be a total of 12 sections for each fuse parent for a total qty of 24 sections 
![image](https://github.com/user-attachments/assets/26a50563-47c5-43f8-9805-6f70a6e5ae4c)

When published to NetSuite section count is 20 not expected 24. 
![image](https://github.com/user-attachments/assets/779b19ab-2a79-4f88-a37b-014baa108349)

**Comment by Reyzerbit** [comment]
@jjohnson2525 Please refer to the "fill center of rectangle" checkbox. When unchecked, it doesn't consider the center pieces of the Fuse structure, so 20 is an accurate count.
