### ISSUE TITLE
Feature: Standalone Drip tray Shape code

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#376]
**Issue:**
We price standalone drip trays pretty often when a customer needs one after the fact of buying a planter. 
So we need to be able to use a drip tray shape code outside of a custom planter parent, to be on it's own line item.

If the shape code needs to be developed please let estimating know so we can get on that. Logic for a Drip tray is different from a standard Rect shape code since there isn't as much welding (majority of cases)
![image](https://github.com/user-attachments/assets/94e83d61-00b0-4bda-b806-64c842b06ad3)

**Comment by Reyzerbit** [comment]
Custom drip trays will now be an option in Ore3D, come next update. Notice: Predesigned drip trays can ONLY be estimated via Abstract Item -> Adding inventory item to BOMs, as it was elected to keep predesigned accessories as inventory items and not Ore3D Builds.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.2](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.2)
