### ISSUE TITLE
Feature: Add Labels to Misc Charges Fields

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#377]
Originally related to https://github.com/Ore-Design/Ore-3D-Reports-Changelog/issues/1187

![image](https://github.com/user-attachments/assets/ba7d7dec-e4f0-4254-9b33-4dff14d6d58f)

Consider consolidating checkboxes. (The pop-out button takes up more space than the 'ignore parent qty' button). 
![image](https://github.com/user-attachments/assets/14229ab7-96c7-4cce-b75a-86abf509a908)

**Comment by Reyzerbit** [comment]
@MattIsrael I'm not sure what you're asking here. You just want me to reduce the size of the pop out button?

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
