### ISSUE TITLE
Limit LF to 2 decimals

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#38]
Can we limit the number of decimals for LF to 2?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/c540d2a3-353b-4f4c-91ef-3e59f792a912)

**Comment by Reyzerbit** [comment]
Completed in [1.0.11](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.11)
