### ISSUE TITLE
Bug: Abstract Duplicate from 1.0 to 2.0 

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#380]
**Bug:**
BOM items changed and i don't understand what exactly happened. This is more of a "heads up" than an actual bug report.

From 1.0 50151
![image](https://github.com/user-attachments/assets/6ef6aa82-5bce-4a1f-8d6e-5115a742ec27)

To 2.0 50750
![image](https://github.com/user-attachments/assets/62f0537b-a8b6-4f42-813b-f0046986b955)

BOM items changed and affected price to a large degree

**Comment by Reyzerbit** [comment]
Complex problem, but we found the cause. If you have questions, come talk to me and/or Jake Drake.
