### ISSUE TITLE
Feature: A sum of the estimated time for each routing from the children on the parent

### ISSUE THREAD

**Issue by LackyLou** [Ore-Design/Ore3DInternal-Reports-Changelog#381]
**Issue:**
Example: Proposal 50784
Issue: There are no estimated times on the line items. 

When I get asked to quote a lead time, I am using the estimated times to help me determine how long it will take to build the product. When it says 0 on the line item for everything, then I have to go into Ore3D and look at each of the children and add them all up to get the total time for each line. This is very time consuming; especially when there are 7 children with multiple quantities on each. 

**Solution:**
Have the total times show up in the parent or have the line item in NS show the total estimated time for each operation.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
