### ISSUE TITLE
Where is "Mouse Hole" flagged?

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#382]
When Mouse Hole is selected, it is not shown on the order.
Reference 50768.

How is this getting flagged for CAD?

![image](https://github.com/user-attachments/assets/0c8e7f17-5608-44d6-a666-be831217861b)
![image](https://github.com/user-attachments/assets/eff09e8b-db2e-4565-93e9-9661013d2ac5)

**Comment by Reyzerbit** [comment]
@jdrake89 @OreController This needs a meeting as no decision was formally made on this. The original predesigned '-MOD' system was vetoed, so we need to come up with a solution. This primarily involves CAD and estimating.

**Comment by OreController** [comment]
Let’s do it, my calendar is up to date.

[Ore Logo]
Tyler Gephart
Assistant Controller

***@***.******@***.***>
→ 801.677.0359

**Comment by jdrake89** [comment]
Mouse hole button need to make Mouse Hole appear in description. It needs to act like the following - Selected - Appears / Not Selected - Nothing appears. This should act in a simialr fashion to drain holes, but not show Y/N on the description. No meeting required, just do it! 
![image](https://github.com/user-attachments/assets/7d779e26-169c-4491-a848-591f3bb2fff3)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
