### ISSUE TITLE
Feature: Propane Tank Holder Name Change to 4100

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#383]
Currently the 4100 (Propane Tank Enclosure) is found in Ore3D under the name "Propane Tank Holder". Can we change that to be found under it's part # 4100??

I can't recall if this is a Batista or Jake Drake thing...

**Comment by jdrake89** [comment]
@Reyzerbit can you look at this one with me?
![image](https://github.com/user-attachments/assets/43a2e248-47b1-46e1-8fbd-e9d82a018b64)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
