### ISSUE TITLE
Bug: Misc Display Button Does not update until after build update

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#384]
Misc charge is always being displayed regardless of the check box being selected. 

![image](https://github.com/user-attachments/assets/d7511775-cfd6-41da-8d93-b77a8b38a723)

![image](https://github.com/user-attachments/assets/16e34cf7-ed2c-4354-9217-32e45bab9267)

**Comment by Reyzerbit** [comment]
Short term fix is to change a dimension and then put it back once that checkbox is clicked (ex. set height to 5 and then back to 18)

**Comment by MattIsrael** [comment]
Can we please increase the priority of this bug. This has and is affecting current proposals AND sales orders.

**Comment by jdrake89** [comment]
Please fix this now. 
![image](https://github.com/user-attachments/assets/f98297e2-9010-458f-97fc-e18e67768744)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
