### ISSUE TITLE
Refreshing Data Base deletes random BOM items in Abstract build

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#385]
I created proposal 50814 this morning.

I had to add an item and refresh my data base.

Refreshing the data based caused ORE3D to delete a random BOM item.

![image](https://github.com/user-attachments/assets/750fa0b7-095c-435c-a6cf-1e46bb95fc2e)

![image](https://github.com/user-attachments/assets/3956fbb7-4601-4766-bede-b44a1d1d3440)

**Comment by MattIsrael** [comment]
can we create a pop up (that you can't get past unless you're admin) that will prompt a user to update their database &/or version?

**Comment by Reyzerbit** [comment]
@daniel11088 are you able to recreate this issue? Or do you have a copy of an old proposal this was made from? I can't seem to recreate this issue on my end.

**Comment by Reyzerbit** [comment]
Unable to recreate
