### ISSUE TITLE
Feature: Improve Cove Pomo Shape Code Description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#387]
Cove pomos are not adding any unique language to the product description.

Needs to include pomo type & what faces the detail occurs on.

I can help more - let me know when you get to this.

**Comment by Reyzerbit** [comment]
@MattIsrael please give me a template for exactly how you want the POMO details to appear on the description.

**Comment by Reyzerbit** [comment]
@MattIsrael any update on this?

**Comment by MattIsrael** [comment]
Nope, sorry. We’re slammed in estimating with Chris and Daniel gone so ALL non-estimating projects are on hold.

[Ore Logo]
Matt Israel
Estimating Manager

***@***.******@***.***>
→ 385.249.1980

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>

**Comment by MattIsrael** [comment]
Haha! You’re a lucky duck Batista. I actually just got a custom pomo RFQ.

**Change default material gauge to .125” AL

Current Description:
Rectangular POMO Planter
Modified Rectangular POMO Planter
L48" x W24" x H28"
Material: Aluminum x 0.190
Finish: Architectural Dark Bronze Powder Coat
Reveal: Skid x 1" height
Drain Holes [Y]
Lip: 1.5

Pomo Type: pull exact language from drop-down
Pomo on # Long Sides
Pomo on # Short Sides

-----------
Example:
Pomo Type: X-Pomo
Pomo on 1 Long Sides
Pomo on 0 Short Sides


[Ore Logo]
Matt Israel
Estimating Manager

***@***.******@***.***>
→ 385.249.1980

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>

From: Matt Israel
Sent: Friday, November 1, 2024 11:45 AM
To: Ore-Design/Ore3DInternal-Reports-Changelog ***@***.***>
Cc: Tyler Gephart ***@***.***>
Subject: RE: [Ore-Design/Ore3DInternal-Reports-Changelog] Feature: Improve Cove Pomo Shape Code Description (Issue #387)

Nope, sorry. We’re slammed in estimating with Chris and Daniel gone so ALL non-estimating projects are on hold.

[Ore Logo]
Matt Israel
Estimating Manager

***@***.******@***.***>
→ 385.249.1980

1972 W 2425 S
Woods Cross, UT 84087

ore.design<https://ore.design/>

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
