### ISSUE TITLE
Bug: Description locked after saving and reopening order

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#388]
Descriptions are being locked after saving and reopening.

This is happening on multiple shape codes, including abstract.

Abstract locks every time after save cycle.

**Comment by Reyzerbit** [comment]
@daniel11088 can you please provide an example proposal/sales order that is doing this?

**Comment by Reyzerbit** [comment]
Looked into the issue, problem is specific to strange characters being used in Netsuite (for example 'ç' in 'façade')

**Comment by MattIsrael** [comment]
REF: 50894
_This is an active customer proposal. Please make a copy and delete / message MI and I'll delete when you're done testing. _

I'm not seeing special characters...

**Comment by Reyzerbit** [comment]
POMOs description have degrees symbol, which is included in the special character restriction.

Only solution is to remove special characters, as it's a NetSuite limitation.

**Comment by Reyzerbit** [comment]
Issue caused because NetSuite parses characters in ISO-LATIN-1, forcing Ore3D to read in ISO-LATIN-1 instead of UTF-8 resolves issue (at least for now)

Fix is associated with changes to [OreNetBridge](https://github.com/Ore-Design/OreNetBridge)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.4](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.4)
