### ISSUE TITLE
Feature: Firepit Process

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore3DInternal-Reports-Changelog#39]
**Issue:**
We need to discuss new process for Firepit creating in Ore3D

**Comment by jdrake89** [comment]
Predesigned Add on components becoming their own buildable items.

Pull together standard / custom logic with add on items and have them add times into overall times. 

Pre-Designed parts will have a -MOD added to the end to signify if standards have custom add on items. 

Batista says I'll have this done by 3/15

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.13](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.13)
