### ISSUE TITLE
Bug: "Options:" Appears in Description Even if NO Options

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#390]
"Options:" is appearing in the product description for custom rectangles even if there are no BOM Options added to the build.

Other 'titles' like this, Notes for example, do not show if there are no notes. 

![image](https://github.com/user-attachments/assets/ed13c885-55a9-43e7-8925-0fc78b4a0b51)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.3.5](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.3.5)
