### ISSUE TITLE
Bug: Misc UOM Not updating automatically in description

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#393]
**Bug:**
UOM that is written in for Misc. Charges does not update in the description without "triggering" it by changing something else in the line item to change the description example: finish or material gauge

UI Issue

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
