### ISSUE TITLE
Feature: Customer Notes in Fuse

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#396]
Get customer notes to appear the same regardless of whether they're in the child or parent. 
It's not advantageous for estimating to put notes in the child because it adds the child name above the note. this is aesthetically different than if we add notes in the parent. It's also confusing because we'll have notes in 2 places.
When working on a large proposal it's easy to accidentally put notes into the child opposed to the parent, where we like them.

Options we came up with - engage us more as needed.

1. Remove child label from Customer Notes put into the child (they go into a list of notes and you can't tell where parent notes start and child notes stop).
2. [and] Parent rolls all child notes up into a single text box. (Notes can be input into the parent or child)
-- Parent note is editable regardless if note was in parent or child.
---- If there is a child note rolling up into the parent note, and it was edited in the parent, opposed to 'overriding' the notes which would allow for different text in parent/child. it would directly 'go back and change' the text in the child. 

4. Eliminate child customer notes

Internal notes are valuable in each child and the parent (as you have it now)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
