### ISSUE TITLE
Bug: Duplicate Powder in BOM: 4051

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#398]
Submitted for Nate. 

4051 is putting duplicate powder items in BOM. Please review similar shape codes for same issue. 

![image](https://github.com/user-attachments/assets/7ac45602-dc7e-46c0-b1aa-e3f9924ec532)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
