### ISSUE TITLE
Feature: Check Box to remove additional BOM items from description (like misc charge)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#399]
additional BOM items currently show up in the product description.

occasionally we don't want to show those - like plumbing components or angle for example.

Can we get a checkbox to hide the additional BOM items from the product description, like we have for misc. items?

**Comment by Reyzerbit** [comment]
Completed in [Release 1.4.0](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.4.0)
