### ISSUE TITLE
Dims not showing up in Water Bowl

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#40]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/876ad6b0-b81e-4bbc-b160-a5001ae1dcfd)

**Comment by Reyzerbit** [comment]
Completed in [1.0.11](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.11)
