### ISSUE TITLE
Bug: Resolve clipping on BOM UOM

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#400]
![image](https://github.com/user-attachments/assets/d82f9ca8-b9c8-4469-b5de-758705056813)

Abbreviate if necessary.

**Comment by Reyzerbit** [comment]
for these to appear abbreviated, you will need to change UOM values in Netsuite. You can talk to @jdrake89 about that

**Comment by jdrake89** [comment]
@Reyzerbit I don't see how I can change the unit of measure abbreviation in NetSuite - it shows as fully written on the drop down menus. Happy to help but not sure how. 
<img width="200" alt="image" src="https://github.com/user-attachments/assets/1ed4dced-a53d-4601-b7b0-54214f8d766d">
