### ISSUE TITLE
Bug: Fuse Fire Pit Descriptions - Not Working

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#417]
The description for Fuse Fire Pits doesn't seem to be rolling up to the parent.

Child:
![image](https://github.com/user-attachments/assets/91f37401-751a-4075-ad00-f8e3dd67bd89)

Parent: 
![image](https://github.com/user-attachments/assets/4d69633a-aba5-4a8c-bd23-a904809e65e5)

The work around for this requires overriding the entire product description. This is a medium-high priority from an estimating perspective.

**Comment by Reyzerbit** [comment]
Please reference comments on existing Fuse Firepit issue #257:

https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/257#issuecomment-2512862767

Fuse Firepits are still "in development" and SHOULD NOT be used in a production setting.

**Comment by MattIsrael** [comment]
Please reopen - not resolved.
