### ISSUE TITLE
Bug: [Sample no worky]

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#45]
Sample no worky

**Comment by jdrake89** [comment]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/bd3aa624-d21e-4d37-bd99-ff79a04e2196)

**Comment by jdrake89** [comment]
The math is not mathing right

**Comment by Reyzerbit** [comment]
BOM is per unit only. Math is correct. Multiplication happens naturally on WO gen.
