### ISSUE TITLE
Fire Pit Lids - Raised Description

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#46]
When you select the raised lid button on a lid, it needs to reflect raised lid in the description. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/16751448-d136-43d9-b253-db1aecc939f7)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/ee596422-aefc-4a18-9131-bd1757fd65ba)

**Comment by Reyzerbit** [comment]
Completed in [1.0.14](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.14)
