### ISSUE TITLE
Panel Fire Pit burners not showing up on sublist

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#47]
Adding in a pan to the 4034 - no burners appear on the list under the fire pan

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/d5d3e6be-26cd-4d93-8ae4-d7c397e931b7)

**Comment by Reyzerbit** [comment]
Fixed
