### ISSUE TITLE
Propane Panel Fire Pit - Too many burner options

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#48]
4040s panel fire pit needs to be limited on the burner options. 

These are built specifically for the LP small tank burners only. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/566fa476-adc3-439a-840b-b5c90ffbd1cc)

**Comment by Reyzerbit** [comment]
Done
