### ISSUE TITLE
4040s glass surrounds are not working correctly.

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#50]
The glass surrounds for the 4040 propane panel fire features are showing modified with incorrect dims. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/11b13496-f60b-46b9-ac85-3fa5769de3e9)

**Comment by Reyzerbit** [comment]
Duplicate of #49
