### ISSUE TITLE
Bug: BOM not filtering by inactives

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#51]
The highlighted graphite powder makes pre-designed products custom. 

I only show 1 graphite (alloy) powder in NetSuite. 

Not sure where this one is coming from. 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/810aea1d-4571-4f6f-83a7-a3fefea69371)

**Comment by Reyzerbit** [comment]
Completed in [1.0.14](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.14)
