### ISSUE TITLE
Searching by NetSuite item number in sub lists

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#52]
We need to be able to search by NetSuite part number and description on the side window sub lists.  

The way its set up when you add a BOM component is ideal. 

<img width="437" alt="image" src="https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/d7a77a03-dce8-419a-b205-5e87a6d75cc9">

<img width="676" alt="image" src="https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/dd522cd4-4b6e-4ffb-8c6d-626a20393f1d">

**Comment by Reyzerbit** [comment]
Completed in [1.0.14](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.14)
