### ISSUE TITLE
FP Burner hidden in $0 child

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#54]
Issues:

1. The burner does not show up in customer facing description.
~~2. We can now add a custom child to a standard build.~~ This is expected
3. Custom child has no dim limitations.
~~4. Child added gets tripled.~~ Moved to seperate bug

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/1d2c2d1a-d240-43c1-992b-6458922522b9)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/655a1f3b-07c1-45be-905a-11e730a587e2)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/467de944-b2f9-4c70-ad6e-97933ccc6a9b)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.15](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.15)
