### ISSUE TITLE
FUSE planter not calculating material correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#57]
Yield and Skids not being calculated correctly.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/eb4791d2-bce9-4646-b463-d5a055c7fdfa)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/1fe8a965-79be-453e-acbd-6820fdc0c3d6)

**Comment by Reyzerbit** [comment]
This is expected behavior. Come talk to me if you have questions regarding this.
