### ISSUE TITLE
PreFab not calculating correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#58]
PreFab is higher in 2.0 in FUSE curved edging.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/326591f4-656d-43b5-b172-5dcf75bf34f0)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6a29fb2d-8046-4668-93b6-099d0c052194)

**Comment by Reyzerbit** [comment]
This is expected. Please come talk to me if you have further questions.
