### ISSUE TITLE
Bug: Certain Specs arent auto-calculating

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#59]
A1110 does not have price or description 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/097099f4-76a2-4f78-acb7-52e863d7d476)

**Comment by daniel11088** [comment]
Price and description magically appear if I save and reopen order.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/e9cd73aa-967f-4145-bbfb-f911315c1cda)

**Comment by daniel11088** [comment]
FUSE children show $0 and FUSE piece length is not populating. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/c759129c-6276-415b-8ec7-9ee264f9c67b)

**Comment by Reyzerbit** [comment]
@daniel11088 I am unable to replicate this. If you can make this happen again, please come show me exactly how you did it.
