### ISSUE TITLE
Feature: Auto-snap Fuse Piece Length and Fuse Piece Width to closest match

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#60]
I can save FUSE Piece Length in a dim that does not divide evenly to the total length and no error message is shown.

The price is based on the FUSE Piece length which does not represent total length.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/d6a3b7b9-b064-4ae7-92e7-2f19e634bfaf)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6567e994-b637-4574-bc59-f3255052e09a)

**Comment by Reyzerbit** [comment]
Planned to resolve this issue by auto-snapping piece length dimensions

**Comment by Reyzerbit** [comment]
Completed in [1.0.14](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.14)
