### ISSUE TITLE
Sheet metal price is cheaper in 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#61]
1/8" in 2.0 is $5.8 and $7.05 in 1.0

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/a8ef6f3b-55cd-4109-9e12-92e8004c844b)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/3c5d662b-9169-4a6a-a564-3a38942f38e1)

.090 in 2.0 is $4.20 and $5.10 in 1.0.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/4f213674-0bac-4b3b-bb17-f78a6c5e8c69)
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/d4192244-6105-44c9-b896-cdce3e47987d)

**Comment by Reyzerbit** [comment]
Please refresh order pricing to resolve.
