### ISSUE TITLE
Repeating Issue: Skids not calculating correctly when "None" is selected.

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#62]
Skids not calculating correctly when "None" is selected.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/ed436bf1-1ffa-4714-8304-04b35791cc9b)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/85c2f90e-2f69-4287-82e2-e6f87e0619b2)

**Comment by Reyzerbit** [comment]
Note to Self: Ignore Height - Reveal Height if RevealType == None

**Comment by Reyzerbit** [comment]
Completed in [1.0.14](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.14)
