### ISSUE TITLE
Reorganize the Planter Tree

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#63]
Can we have the High, Low and Mid rectangles either in the same drop down or in order so they grouped together?

Also, can we get rid of this below?
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1177d2a6-ecb9-4a5f-b27f-a7ab897397a3)

**Comment by Reyzerbit** [comment]
Done
