### ISSUE TITLE
Bug: Finish part # should not be in item description

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#70]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/ac5dde9d-6bf6-49fa-980e-e6fe63c399e6)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.16](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.16)
