### ISSUE TITLE
Bug: Material not calculated correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#72]
Please verify what is being calculated.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/b7462802-2411-4bcb-9fe0-c254b8bb9cba)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/9b4d17b5-8c68-4faa-8710-45c03208b879)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.16](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.16)
