### ISSUE TITLE
Oxidize Zinc Patina not calculating correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#73]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/900b78af-50c7-42ae-928c-953f5ec7a182)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/ba9584c2-8b4c-45c0-a82f-51dd9f236412)

**Comment by Reyzerbit** [comment]
Related to #72
