### ISSUE TITLE
Bug: Should not allow for finish to =null

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#77]
when searching for a finish the blank lines in the 'results' are selectable - they should not be. 

Selecting a blank line removes finish from the BOM and pushes the element into Modified - should not be possible. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/725512e4-41a6-4dfc-a27b-0907c03037d5)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.16](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.16)
