### ISSUE TITLE
Feature: Sort, reduce length of fire pit options & add some type of descriptions

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#78]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/204aff27-942b-427f-95c6-cb2bd14f99be)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)
