### ISSUE TITLE
Bug: Drip Trays V2.0.12 - Make it Behave like V1.0

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#8]
**Bug:**
Add Child drip tray:
•	Standards:
o	Should pull BOM item for Drip tray and Add it
o	Same Behavior as Ore3D V.1.0
o	 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/2dbbdbe6-5449-4584-9d01-da0c3d446d27)

•	Custom: 
o	Should pull L x W from parent. H=1.5” but still Editable
o	Same Behavior as V1.0
o	 
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/19011f2c-d8aa-46ae-a28b-b879b505464a)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
