### ISSUE TITLE
Bug: Burner not constrained by pan dimensions

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#80]
Pan needs to be =to or > burner dims.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/514d34fc-d064-4c2a-a0c6-e3e438a4c12b)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.16](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.16)
