### ISSUE TITLE
Bug: Duplicate burner?

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#81]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/f9897c00-5309-4e14-9d55-e7c13f762ff1)

4020

**Comment by Reyzerbit** [comment]
Referred to Jake Drake

**Comment by jdrake89** [comment]
These are because we had multiple inventory items for the same burner. 4012 and 4013 share the same burner. We can go through the list and deactivate duplicates.
