### ISSUE TITLE
Bug: A6001 - FACADE CUBE 6001-6007 - Routings review 

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#84]
Here is my first pass review. Please let me know if you have questions 

A6001: 
- ~~CAD needs to be zero~~
- ~~FAB maybe low at 260~~
- Pkg high at 110 (Should match A6003 & A6004)
- material low at 19sf. (Internal panels for cladding need to be 1/8"AL) 
- Rail should be [100-6027] Vee 20 OAK Toffee

A6002:
- ~~CAD needs to be zero~~
- ~~FAB maybe low at 260~~
- Pkg high at 110 (Should match A6003 & A6004)
- material low at 19sf. (Internal panels for cladding need to be 1/8"AL) 
-  Rail should be [100-6019] Vee 20 OAK Malt

A6003:
- Description doesn't display predesigned 
-  Dimensions are incorrect 
- ~~CAD needs to be zero~~
- ~~FAB maybe low at 260~~
- Pkg high at 106 (Should match A6001 & A6002)
- material low at 19sf. (Internal panels for cladding need to be 1/8"AL) 
- Rail should be [100-6027] Vee 20 OAK Toffee

A6004:
- Description doesn't display predesigned
- Dimensions are incorrect 
- ~~CAD needs to be zero~~
- ~~FAB maybe low at 260~~
- Pkg high at 106 (Should match A6001 & A6002)
- material low at 19sf. (Internal panels for cladding need to be 1/8"AL)
- Rail should be [100-6019] Vee 20 OAK Malt

A6005:
- ~~CAD needs to be zero~~ 
- Material low at 19sf. (Internal panels for cladding need to be 1/8"AL)
- Pkg high at 78

A6006: 
- ~~CAD needs to be zero~~ 
- Material low at 19sf. (Internal panels for cladding need to be 1/8"AL)
- No rail LF included in BOM. Need to add [100-6022] Surface 100 Oak Malt

A6007:
- ~~CAD needs to be zero~~ 
-FAB low at 298 (Need fab time for the al slats) 
- Material low at 19sf. (Internal panels for cladding need to be 1/8"AL & Need 1/8"AL for slats )

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.16](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.16)
