### ISSUE TITLE
Assebmlies in WO are not comming acccrross as phantoims

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#87]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/0f4761b5-2697-4133-a9bb-c93421cd382b)
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/83c0ffe8-4238-49bb-b4c0-bf709a86cc9f)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)
