### ISSUE TITLE
WO are being made out of sequence to the lines items 

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#88]
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/136127203/c95ba7ba-61f5-4628-8d2c-9d3f8f43f2dc)

**Comment by Reyzerbit** [comment]
In order to maintain the best efficiency possible, we probably wont do anything about this. The order of the WO is not all that important.
