### ISSUE TITLE
Reveal  in description needs to read 0 if none is selected

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#9]
Can we make reveal read 0 if none is selected?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/f210819e-3cc1-43e3-821d-4d63fe937d20)

**Comment by Reyzerbit** [comment]
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)
