### ISSUE TITLE
Reveal Height still calculating when Type is set to None

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#90]
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/57e33235-6d70-4a8d-99b3-12b74c79dcbd)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/cee981a2-013e-4c70-ba66-f4b396b09ca4)

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)
