### ISSUE TITLE
Inset dims to be set to 0 for L and W

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#91]
Please set inset dims to 0L and 0W.

Skids and skirts should be calculating full perimeter of planter.

This is for FUSE and NonFUSE.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/d51b6db9-714e-422e-be05-6c89d75b1036)

**Comment by Reyzerbit** [comment]
This has already been discussed and rejected as a request as it is inaccurate information. This information is needed by CAD, supply chain, and operations.
