### ISSUE TITLE
Copy from 1.0 to 2.0

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#93]
It might be easier to meet about these.

Copy Issues:
•	FUSE
o	Child price is multiplied by number of children from 1.0 and maintains same number of children in copy
o	Routing overrides do no transfer
o	BOM overrides transfer over but is not multiplied by number of children. (I think. Unable to see BOM per child in 2.0. Feature request submitted. Bug Ore-Design/Ore-3D-Reports-Changelog#946)
•	Pre-Designed
o	Catalog pricing does not transfer for all products
o	A1021 does not transfer IPE Band price
o	Water Features do not transfer price of components or Routings
o	Children do not transfer routings (ex drip tray)
o	BOM components do not transfer
 
Things that work:
•	Description
•	Notes (Internal/Customer)
•	Pre-Designs with out components attached (ex: 1110)
•	Modified with out children
 
Test proposals:
1.0 - 47820 - Pre-Designed/Modified: Planters, Water Features, Seating 
2.0 - 47837 - Pre-Designed/Modified: Planters, Water Features, Seating 
 
1.0 - 47830 - Fuse (Complex)
2.0 - 47852 - Fuse (Complex)
 
1.0 - 47823 - 47823 - Fuse (Simple)
2.0 - 47851 - 47823 - Fuse (Simple)

**Comment by Reyzerbit** [comment]
First issue found: Ore3D 2.0 doesn't recognize band planters vs regular planters. Fixing this will resolve:
o A1021 does not transfer IPE Band price

**Comment by Reyzerbit** [comment]
Drip trays were not being read AT ALL. Fixing this will resolve:
o Children do not transfer routings (ex drip tray)

**Comment by Reyzerbit** [comment]
o Child price is multiplied by number of children from 1.0 and maintains same number of children in copy

This is expected. There isn't really a good way to tell how things were split when converting from 1.0 to 2.0, so this has to be the workaround until then.

**Comment by Reyzerbit** [comment]
It seems that the only unfixable problem we have is the water feature. Me and Jake Drake will be working on a resolution.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)
