### ISSUE TITLE
Custom Fire Feature issues

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#96]
- Pan not adding dollar value to parent
- Can pan dims be driven by burner dims?
- Burner price not shown in parent
- "Matches Parent" button for glass surround does not work 
- Can Lid finish auto select to body finish?
- Can Lid auto fill dims from pan?

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/6f4d102b-7405-4895-86a0-20dd47b7b13b)

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/908cad34-5d41-47d7-bdfc-cbe06406e601)

**Comment by Reyzerbit** [comment]
- Pan not adding dollar value to parent
   ∟ This is expected. It's a system Jake Drake and I created. Come talk to me if you have questions
- Can pan dims be driven by burner dims?
   ∟ Short answer is no. Sometimes pan dims wont match burner (we make pans that are bigger than the burner)
- Burner price not shown in parent
   ∟ Not sure what you mean by this? The burner isn't supposed to show up in the parent
- "Matches Parent" button for glass surround does not work 
   ∟ I'll fix this
- Can Lid finish auto select to body finish?
   ∟ Do you mean on add, or when the "matches parent" is selected?
- Can Lid auto fill dims from pan?
   ∟ Maybe? Ill talk to CAD about it.

**Comment by jdrake89** [comment]
Pan not adding dollar value to parent
∟ This is expected. It's a system Jake Drake and I created. Come talk to me if you have questions


*Batista and I reviewed, he is going to work on this fix.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)
