### ISSUE TITLE
Remove -MOD System

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/Ore3DInternal-Reports-Changelog#98]
Matt Israel and Grif have requested that we undo the -MOD system and prevent custom addons under pre-designed products.

Per MI's email 3/19
Pre-Designed Fire Features:
•	NO ABILITY TO CUSTOMIZE OPTIONS (lid, pan or glass surround)
o	Please lock out fields, but you’re welcome to leave existing functionality in Ore3D for potential future use.

Modified Fire Feature
•	Full ability to customize these elements
•	Description Request: GRAB ME SO WE CAN DEVELOP THE DESCRIPTION TOGETHER
o	Pans: 
	Need L, W, H dimensions
o	Lids and glass surrounds
	Need L, W, H dimensions
	Need finish

Drip Trays:
•	NO ABILITY TO CUSTOMIZE DRIP TRAY UNDER PRE-DESIGNED PLANTER. 
•	If you need a custom drip tray the planter will need to be bid as modified(custom)
•	**Unable to provide L, W, H dimensions to flag as pre-designed. H changes based on option integration.** 

Jake Drake, are there any other stakeholders this concerns that we would need to schedule a meeting for?

**Comment by jdrake89** [comment]
I think this is a good idea, no concerns from me. We will have to inform the Sales and PM team about this, but not a concern for a meeting.

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
