### ISSUE TITLE
Bison Pre-Built Inventory

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#99]
Need to build Bison shape codes into a 3 part system:

"Normal"
"Un-finished"
"Pre-built finished"

Normal stays the same as built now. The other 2 are locked with the following parameter:

<img width="584" alt="image" src="https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/c074cff7-d86f-4363-b1f2-a463d7eca66a">

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.17](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.17)

**Comment by jdrake89** [comment]
@Reyzerbit I messed up and forgot to have the irrigation tube added to the pre-built inventory. Can we reopen this and get the irrigation sleeves added?

"Includes Bison Logo & Irrigation Tube"

**Comment by Reyzerbit** [comment]
Completed in [Release 1.0.18](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.18)
